### PR TITLE
I have the feeling that it breaks with bazel 0.5.3

### PR DESCRIPTION
**Pull request by apelisse**
Let's see what travis thinks about that.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by apelisse** [comment]
OK Actually looks good. Thank you Travis

**Comment by ixdy** [comment]
It looks like older snapshots of `rules_go` (in Kubernetes' case, /03c634753160632c00f506afeafc819fbea4c422) are compatible with Bazel 0.5.3, though.

I'm working on bumping our `rules_go` dependency for the master branch, but this is painful for the release branches.

**Comment by apelisse** [comment]
> It looks like older snapshots of rules_go (in Kubernetes' case, 03c6347) are incompatible with Bazel 0.5.3, though.

Did you really mean are or aren't?

**Pull request closed without merging**
