### PR TITLE
Use Label and GoArchiveData.name when constructing pkg.json files

### LINKED ISSUE #2948: Go packages driver sometimes doesn't work with test files
I'm having an issue getting the updated Go packages driver working for some, but not other, test files. I've created a minimal repro to trigger the issue which appears to be related to dependencies of libraries not appearing on test targets. More info inline.

### What version of rules_go are you using?
70b8365a90e226b98f66bc35d3abb3e335883d81

### What version of gazelle are you using?
0.22.3

### What version of Bazel are you using?
4.2.1

### Does this issue reproduce with the latest releases of all the above?
Yes, this report is specifically about the latest Go packages driver.

### What operating system and processor architecture are you using?
macOS on x86-64

### Any other potentially useful information about your toolchain?
Nothing relevant

### What did you do?
I made a repo to reproduce this issue here: https://github.com/csstaub/gopackagesdriver-repro

Note that in the repro, `c:go_default_library` imports A/B, but the test target does not as the dependencies are not used in the tests explicitly. This builds fine because `c:go_default_test` has an `embed` with `c:go_default_library`, my understanding here is that the deps on the library hence become transitive deps of the test target.

But, if I run the Go packages driver for the test file, it reports no packages for `c_test.go`:
```
❯❯❯ echo '{}' | ./tools/gopackagesdriver.sh 'file=src/c/c_test.go'
INFO: Analyzed target @io_bazel_rules_go//go/tools/gopackagesdriver:gopackagesdriver (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target @io_bazel_rules_go//go/tools/gopackagesdriver:gopackagesdriver up-to-date:
  bazel-bin/external/io_bazel_rules_go/go/tools/gopackagesdriver/gopackagesdriver_/gopackagesdriver
INFO: Elapsed time: 0.280s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Running: [bazel info --tool_tag=gopackagesdriver --ui_actions_shown=0]
Running: [bazel query --tool_tag=gopackagesdriver --ui_actions_shown=0 --ui_event_filters=-info,-stderr --noshow_progress --order_output=no --output=label --nodep_deps --noimplicit_deps --notool_deps kind("go_library|go_test", same_pkg_direct_rdeps("src/c/c_test.go"))]
Running: [bazel build --tool_tag=gopackagesdriver --ui_actions_shown=0 --show_result=0 --build_event_json_file=/var/folders/p1/r8r4p94n281gfxs_p3jd38zh0000gn/T/gopackagesdriver_bep_95385647 --build_event_json_file_path_conversion=no --experimental_convenience_symlinks=ignore --ui_event_filters=-info,-stderr --noshow_progress --aspects=@io_bazel_rules_go//go/tools/gopackagesdriver:aspect.bzl%go_pkg_info_aspect --output_groups=go_pkg_driver_json_file,go_pkg_driver_stdlib_json_file,go_pkg_driver_srcs --keep_going //src/c:go_default_test]
ERROR: command succeeded, but not all targets were analyzed
{"NotHandled":false,"Sizes":{"WordSize":8,"MaxAlign":8},"Packages":[]}
```

Getting packages for `c.go` works fine:
```
❯❯❯ echo '{}' | ./tools/gopackagesdriver.sh 'file=src/c/c.go'
INFO: Analyzed target @io_bazel_rules_go//go/tools/gopackagesdriver:gopackagesdriver (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target @io_bazel_rules_go//go/tools/gopackagesdriver:gopackagesdriver up-to-date:
  bazel-bin/external/io_bazel_rules_go/go/tools/gopackagesdriver/gopackagesdriver_/gopackagesdriver
INFO: Elapsed time: 0.272s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Running: [bazel info --tool_tag=gopackagesdriver --ui_actions_shown=0]
Running: [bazel query --tool_tag=gopackagesdriver --ui_actions_shown=0 --ui_event_filters=-info,-stderr --noshow_progress --order_output=no --output=label --nodep_deps --noimplicit_deps --notool_deps kind("go_library|go_test", same_pkg_direct_rdeps("src/c/c.go"))]
Running: [bazel build --tool_tag=gopackagesdriver --ui_actions_shown=0 --show_result=0 --build_event_json_file=/var/folders/p1/r8r4p94n281gfxs_p3jd38zh0000gn/T/gopackagesdriver_bep_159641577 --build_event_json_file_path_conversion=no --experimental_convenience_symlinks=ignore --ui_event_filters=-info,-stderr --noshow_progress --aspects=@io_bazel_rules_go//go/tools/gopackagesdriver:aspect.bzl%go_pkg_info_aspect --output_groups=go_pkg_driver_json_file,go_pkg_driver_stdlib_json_file,go_pkg_driver_srcs --keep_going //src/c:go_default_library]
{"NotHandled":false,"Sizes":{"WordSize":8,"MaxAlign":8},"Roots":["//src/c:go_default_library"],"Packages":[{"ID":"//src/c:go_default_library","Name":"c","PkgPath":"example.com/c","GoFiles":["/Users/cstaub/Development/repro/src/c/c.go"],"CompiledGoFiles":["/Users/cstaub/Development/repro/src/c/c.go"],"ExportFile":"/private/var/tmp/_bazel_cstaub/821bede8a48c2229d6e91ced1c40f8a6/execroot/__main__/bazel-out/darwin-fastbuild/bin/src/c/go_default_library.x","Imports":{"example.com/a":"//src/a:go_default_library","example.com/b":"//src/b:go_default_library"}},{"ID":"//src/a:go_default_library","Name":"a","PkgPath":"example.com/a","GoFiles":["/Users/cstaub/Development/repro/src/a/a.go"],"CompiledGoFiles":["/Users/cstaub/Development/repro/src/a/a.go"],"ExportFile":"/private/var/tmp/_bazel_cstaub/821bede8a48c2229d6e91ced1c40f8a6/execroot/__main__/bazel-out/darwin-fastbuild/bin/src/a/go_default_library.x"},{"ID":"//src/b:go_default_library","Name":"b","PkgPath":"example.com/b","GoFiles":["/Users/cstaub/Development/repro/src/b/b.go"],"CompiledGoFiles":["/Users/cstaub/Development/repro/src/b/b.go"],"ExportFile":"/private/var/tmp/_bazel_cstaub/821bede8a48c2229d6e91ced1c40f8a6/execroot/__main__/bazel-out/darwin-fastbuild/bin/src/b/go_default_library.x"}]}
```

Not sure why this is -- I can get it to produce different outputs if I make the deps explicit, and/or add one but not both, to the test target. 

### What did you expect to see?
Package info for the test file.

### What did you see instead?
No package info for the test file.

### PR DESCRIPTION
**Pull request by aignas**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

Use the package name in the pkg.json for each dependency in a particular target when processing a request from gopls. This ensures that separate packages that have the same package name but different import paths do not collide and that each import map to a unique pkg.json file during the analysis step.

**Which issues(s) does this PR fix?**

Fixes #2948

### CODE REVIEW

**Comment by aignas** [comment]
I think this is ready for a first round of reviews.

**Comment by aignas** [comment]
Hi, @linzhp, do you know what would be the process to get this reviewed and potentially merged?

Sorry for the direct ping.

**Comment by linzhp** [comment]
Steve is on paternity leave. I can take a look this week. Ping me again if you don't hear back before next week.

**Review by linzhp — COMMENTED** [review]
Sorry for the delay. I think the root cause of this issue is the `go_pkg_info_aspect` of a `go_test` target writes the `pkg.json` file for other packages in its own directory, although the `pkg.json` of those package are already in their own directory.

After cloning https://github.com/csstaub/gopackagesdriver-repro and applying your pull request, I found:

```
$ bazel build --output_groups=go_pkg_driver_json_file --aspects=@io_bazel_rules_go//go/tools/gopackagesdriver:aspect.bzl%go_pkg_info_aspect //src/c:go_default_test
INFO: Analyzed target //src/c:go_default_test (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Aspect @io_bazel_rules_go//go/tools/gopackagesdriver:aspect.bzl%go_pkg_info_aspect of //src/c:go_default_test up-to-date:
  bazel-bin/src/a/srcZaZgo_default_libraryZgo_default_library.pkg.json
  bazel-bin/src/b/srcZbZgo_default_libraryZgo_default_library.pkg.json
  bazel-bin/src/c/srcZcZgo_default_testZgo_default_test~testmain.pkg.json
  bazel-bin/src/c/srcZaZgo_default_libraryZgo_default_library.pkg.json
  bazel-bin/src/c/srcZbZgo_default_libraryZgo_default_library.pkg.json
  bazel-bin/src/c/srcZcZgo_default_testZgo_default_test.pkg.json
  bazel-bin/src/c/srcZcZgo_default_testZgo_default_test_test.pkg.json
  bazel-bin/src/c/goZtoolsZbzltestutilZbzltestutilZbzltestutil.pkg.json
```

We can see there is a `bazel-bin/src/a/srcZaZgo_default_libraryZgo_default_library.pkg.json` and a `bazel-bin/src/c/srcZaZgo_default_libraryZgo_default_library.pkg.json`, but the two `pkg.json` files are exactly the same.

So I think the correct fix is to avoid writing the same `srcZaZgo_default_libraryZgo_default_library.pkg.json` again in `bazel-bin/src/c`, which would avoid the name collision without the lengthy file name and potential performance improvement with reduced I/O.

**Comment by skevy** [comment]
@linzhp I ran into this recently and decided to take a deeper look, keeping in mind your comment.

After reading your comment above and looking at the code deeper, I'm not quite sure I understand why we're even trying to generate json files for _all_ the direct dependencies of the test target, as they should be generated when the aspect visits the `go_library` definition that's embedded in the `go_test` rule, which it will always do.

In my testing, I changed the code to just be:

```starlark
if ctx.rule.kind == "go_test":
    for dep_archive in archive.direct:
        if archive.data.label == dep_archive.data.label:
            pkg = _go_archive_to_pkg(dep_archive)
            pkg_json_files.append(_make_pkg_json(ctx, dep_archive, pkg))
            compiled_go_files.extend(dep_archive.source.srcs)
            export_files.append(dep_archive.data.export_file)
```

which just looks for the archive in the direct deps that that contains the test sources and has the same label as the parent test archive (which, in my testing, always exists).

This makes sure that we have a pkg json generated with the test sources, but it doesn't re-generated pkg.json's for all dependencies, because those, as you pointed out, should already exist when they were generated in a different target.

This seems to work in my testing.

Thoughts?

cc @aignas @steeve @esprehn

**Comment by aignas** [comment]
Thanks for the comment @skevy, I am working on a new version of the PR, which ensures that the test target related `pkg.json` files are generated correctly. I am still trying to understand why the code is the way it is (i.e. why we were using `importpath` for the test targets). I'll look at your solution as well.

**Comment by linzhp** [comment]
Superseded by #3111

**Pull request closed without merging**
