### PR TITLE
toolchain: add 1.8.4 and 1.9.1 releases.

### PR DESCRIPTION
**Pull request by diegs**
Also updates the default to 1.9.1. This is a security release:

https://groups.google.com/forum/m/#!topic/golang-nuts/sHfMg4gZNps

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by diegs** [comment]
I appear to be covered by a corporate CLA already.

**Comment by diegs** [comment]
Signed an individual CLA too, why not.

**Comment by diegs** [comment]
Fixes #875

**Pull request merged**
