### PR TITLE
Prepare release v0.33.0

### PR DESCRIPTION
**Pull request by fmeum**
# Release Notes

## Breaking changes

* [cover](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst#cover) has been removed in v0.32.0. Please [leave a comment](https://github.com/bazelbuild/rules_go/issues/3168) if you are affected by this.

## Deprecations

* The [asm](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst#asm), [compile](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst#compile), and [pack](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst#pack) action generators provided by [go_context](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst#go_context) are deprecated and planned for removal in version v0.36.0. Please leave a comment on the [tracking bug](https://github.com/bazelbuild/rules_go/issues/3168) if [archive](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst#archive) and [link](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst#link) are not suitable replacements for your use cases.

## Bug Fixes

* @sluongng fixed a race condition that could cause non-sandboxed builds of `go_test` targets to fail (https://github.com/bazelbuild/rules_go/pull/3145) 
* @abhinav made `//go:embed` work with `go_path` (https://github.com/bazelbuild/rules_go/pull/3163)
* @xytan0056 made gopackagesdriver work with Go 1.18 (https://github.com/bazelbuild/rules_go/pull/3157)
* @nickgooding ensured that `gomock` can be used with any Gazelle naming convention (https://github.com/bazelbuild/rules_go/pull/3155)
* `go_library` targets using CGo can now reference unresolved symbols (https://github.com/bazelbuild/rules_go/pull/3174) 

Thanks to all of the contributors!

## Compatibility

The minimum required version of Bazel remains at 4.2.1.

## Updated dependencies

* Updated `org_golang_x_sys`, `org_golang_x_xerrors`, `org_golang_google_genproto`, `go_googleapis` to their most recent commit as of 2022-06-05

As always, you can use higher versions of rules_go's dependencies by declaring them in WORKSPACE before calling go_rules_dependencies. Lower versions may work but are not supported.

## WORKSPACE code

// TBD after release

### CODE REVIEW

**Comment by sluongng** [comment]
Would be nice to get a gazelle release coupled with this. ❤️

**Comment by sluongng** [comment]
> Please leave a comment on the tracking bug if archive and link are not suitable replacements for you use cases.

s/you/your/

**Review by linzhp — APPROVED** [review]

**Comment by fmeum** [comment]
Will try to fix https://github.com/bazelbuild/rules_go/issues/3178 for this release.

**Comment by linzhp** [comment]
Do you want to upgrade x_tools too? It's been while since last upgrade

**Comment by fmeum** [comment]
I remember you saying something about gazelle having to update x_mod first. Has that been done?

**Comment by linzhp** [comment]
yeah, but I am wondering whether we can make rules_go not relying on Gazelle's version of x_mod. If that's not possible, maybe we should upgrade x_mod in Gazelle and release a new version of Gazelle? It's been a while since last release.

**Comment by fmeum** [comment]
That seems difficult - we would probably have to get it with a `git_repository` and patch in BUILD files. Should I also do the Gazelle release? I don't know the project well though.

**Comment by fmeum** [comment]
Confirmed that Gazelle tests pass with rules_go at this PR with the latest commit fixing `bzl_library` deps.

**Comment by sluongng** [comment]
just a small note: we should look into how to de-noise the `*.patch` files. All the diff seems to be just changing the time stamp in the generated diff which is not useful to review.

**Review by sluongng — APPROVED** [review]

**Comment by sluongng** [comment]
https://github.com/bazelbuild/rules_go/blob/master/go/tools/releaser/upgradedep.go#L539-L559 It seems like we do intended to sanitize the patch file from timestamp, but there is a bug that make it fail? 🤔

**Pull request merged**
