### PR TITLE
discrimante on test func signatures when generating tests

### PR DESCRIPTION
**Pull request by mikedanese**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by mikedanese** [comment]
Hi Clayton, while the discriminators I added are always true, the discriminator for the referenced type "testing" is not true if the "testing" package was aliased to some other name. Why anyone would do that, I'm not sure. I can definitely extract that information by running the typechecker but I can't decide if that is overkill for this.

**Comment by pmbethe09** [comment]
LGTM, just need to fix merge conflicts.

**Comment by smarterclayton** [comment]
Might be overkill, but I've seen aliases of "testing" in the wild (probably one in a thousand).

**Comment by pmbethe09** [comment]
Jenkins, test this please.

**Pull request merged**
