### PR TITLE
Fixes go rules so that target names with slash characters can be used.

### PR DESCRIPTION
**Pull request by robotoer**
Addresses https://github.com/bazelbuild/rules_go/issues/430

Replaces `/` characters with `_` in golang target names.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by robotoer** [comment]
This fix does open up a new issue where if you were to have two go_libraries defined as such:
```
go_library(
    name="my/target/name",
    ...
)

go_library(
    name="my_target_name",
    ...
)
```

The build would fail as those two targets would create files with the same names.

**Comment by jayconrod** [comment]
Thanks for sending this PR. #430 is definitely a problem we should fix, but I'm concerned this solution will break the correspondence between Bazel labels, output files, and Go import paths. Since this changes the output file name, the compiler and linker would not be able to find the correct dependencies. I don't think we have any tests that cover that, but we'll add some.

I'll add some more comments on #430.

**Comment by robotoer** [comment]
No longer necessary as this has been fixed in #429

**Pull request closed without merging**
