### PR TITLE
Re-enable go_path_test on RBE

### PR DESCRIPTION
**Pull request by sluongng**
**What type of PR is this?**

> Uncomment one line below and remove others.
>
Bug fix

**What does this PR do? Why is it needed?**

Re-enable GoPath action to test against RBE now that symlinks are handled correctly.

**Which issues(s) does this PR fix?**

Fixes #

**Other notes for review**

### CODE REVIEW

**Comment by sluongng** [comment]
@fmeum this change is realtively straight forward. Since you touched symlink code on Bazel side, could you please give it a quick look?

**Comment by fmeum** [comment]
@sluongng We could add a feature for `declare_symlink` being available by default to `bazel_features` and start using it if it is available. What do you think?

**Comment by fmeum** [comment]
@sluongng That warning should definitely go away, the feature is stable - toggling it off is what may not work as expected at this point. The issue you linked isn't directly related, it's about `ctx.actions.symlink`, not `ctx.actions.declare_symlink`.

**Comment by sluongng** [comment]
Ah I was confusing the 2 😵‍💫 

Yup, happy to depend on https://github.com/bazel-contrib/bazel_features and switch to `ctx.actions.declare_symlink` when it's available.

**Comment by sluongng** [comment]
Sent https://github.com/bazelbuild/bazel/pull/18313

**Pull request merged**
