### PR TITLE
Add protocopt option to protoc go compiler

### LINKED ISSUE #2673: Support proto3 optional fields
### What version of rules_go are you using?

Master 312a801084712314ea7da6f1c226306af58eb097

### What version of gazelle are you using?

N/A or latest

### What version of Bazel are you using?

3.6.0

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

linux amd64

### Any other potentially useful information about your toolchain?

The "optional" label was removed when proto3 was released. However, it was introduced to proto3 in version 3.12.0.
See more info here: https://github.com/protocolbuffers/protobuf/blob/e2cc2de304f8bc33b91ab18fa0b7cef8aaf26c8b/docs/field_presence.md

### What did you do?

First, I updated `com_google_protobuf` to v3.13.0 (requires at least v3.12.0 for optional support in proto3).

So I am trying to use a proto3 message with an optional field. For example:

```protobuf
// tests/core/go_proto_library/optional.proto
syntax = "proto3";

option go_package = "github.com/bazelbuild/rules_go/tests/core/go_proto_library/protos";

message Optional {
  optional uint64 a = 1;
}
```

When I run this with protoc, then it works as expected when I provide the flag `--experimental_allow_proto3_optional`.

```
➜  rules_go git:(master) ✗ /home/preston/.local/bin/protoc --version   
libprotoc 3.13.0
➜  rules_go git:(master) ✗ /home/preston/.local/bin/protoc --experimental_allow_proto3_optional tests/core/go_proto_library/optional.proto --go_out=/tmp/ 

# produces expected file /tmp/github.com/bazelbuild/rules_go/tests/core/go_proto_library/protos/optional.pb.go
```

I added this proto and a basic test

```diff
--- a/tests/core/go_proto_library/BUILD.bazel
+++ b/tests/core/go_proto_library/BUILD.bazel
@@ -123,6 +123,25 @@ go_test(
     deps = [":protos_go_proto"],
 )
 
+go_test(
+    name = "optional_test",
+    srcs = ["optional_test.go"],
+    deps = [":optional_go_proto"],
+)
+
+go_proto_library(
+    name = "optional_go_proto",
+    importpath = "github.com/bazelbuild/rules_go/tests/core/go_proto_library/protos",
+    protos = [
+        ":optional_proto",
+    ]
+)
+
+proto_library(
+    name = "optional_proto",
+    srcs = ["optional.proto"],
+)
+
 go_proto_library(
     name = "protos_go_proto",
     importpath = "github.com/bazelbuild/rules_go/tests/core/go_proto_library/protos",
```

```go
// tests/core/go_proto_library/optional_test.go
package protos_test

import (
        "testing"

        "github.com/bazelbuild/rules_go/tests/core/go_proto_library/protos"
)

func use(interface{}) {}

func TestProtosWithOptional(t *testing.T) {
        use(protos.Optional{})
}
```

At this point, I am stuck / lost on where to add the flag `--experimental_allow_proto3_optional` to protoc. 
This issue might be a rules_proto issue, so I have also filed https://github.com/bazelbuild/rules_proto/issues/71. 

### What did you expect to see?

It works as intended.

### What did you see instead?

```
tests/core/go_proto_library/optional.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.
```
Full log below
```
bazel test //tests/core/go_proto_library:optional_test
INFO: Invocation ID: c3339e91-610f-459a-92fe-97884f266bbc
INFO: Streaming build results to: https://builds.prylabs.net/invocation/c3339e91-610f-459a-92fe-97884f266bbc
DEBUG: Rule 'com_google_protobuf' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "9b4ee22c250fe31b16f1a24d61467e40780a3fbb9b91c3b65be2a376ed913a1a"
DEBUG: Repository com_google_protobuf instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/preston/.cache/bazel/_bazel_preston/86fca68c03a78f7c75ec8774faa99d1e/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Analyzed target //tests/core/go_proto_library:optional_test (3 packages loaded, 29 targets configured).
INFO: Found 1 test target...
ERROR: /tmp/rules_go/tests/core/go_proto_library/BUILD.bazel:140:14: Generating Descriptor Set proto_library //tests/core/go_proto_library:optional_proto failed (Exit 1) protoc failed: error executing command bazel-out/host/bin/external/com_google_protobuf/protoc '--descriptor_set_out=bazel-out/k8-fastbuild/bin/tests/core/go_proto_library/optional_proto-descriptor-set.proto.bin' ... (remaining 5 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
tests/core/go_proto_library/optional.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.
Target //tests/core/go_proto_library:optional_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.696s, Critical Path: 0.12s
INFO: 6 processes: 6 internal.
//tests/core/go_proto_library:optional_test                     FAILED TO BUILD

Executed 0 out of 1 test: 1 fails to build.
INFO: Streaming build results to: https://builds.prylabs.net/invocation/c3339e91-610f-459a-92fe-97884f266bbc
FAILED: Build did NOT complete successfully
```

### PR DESCRIPTION
**Pull request by prestonvanloon**
**What type of PR is this?**

Feature

**What does this PR do? Why is it needed?**

This PR allows for downstream projects to define a go proto compiler that requires additional protoc arguments.

Example usage:
```starlark
go_proto_compiler(
    name = "go_cast_grpc",
    options = [
        "plugins=grpc",
    ],
    plugin = ":protoc-gen-go-cast",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_golang_protobuf//proto:go_default_library",
        "@org_golang_google_grpc//:go_default_library",
        "@org_golang_google_grpc//codes:go_default_library",
        "@org_golang_google_grpc//status:go_default_library",
        "@org_golang_google_protobuf//reflect/protoreflect:go_default_library",
        "@org_golang_google_protobuf//runtime/protoimpl:go_default_library",
    ],
    protocopts = ["--experimental_allow_proto3_optional"], # Additional requirement for this compiler to use proto3 optionals
)
```

**Which issues(s) does this PR fix?**

Fixes #2673

**Other notes for review**

Opening as a draft to solicit early review. 
This is missing any form of tests would like to receive some feedback from maintainers before proceeding.

Ideally, this functionality would be better implemented if the `--protocopt` flag was exposed via the starlark API, i.e. `--protocopt=--experimental_allow_proto3_optional` in the command line, however, it does not seem possible to access this flag in starlark. So, I have taken this approach to allow the arguments to be provided as target attributes on the go_proto_compiler rule.

### CODE REVIEW

**Comment by jayconrod** [comment]
@bazelbuild/go-maintainers Please comment if you have any thoughts on this PR.

**Comment by achew22** [comment]
LGTM, would it be possible to add a testcase that exercises this?

**Comment by prestonvanloon** [comment]
Added test scenario for this PR. Thanks!

**Comment by achew22** [comment]
Hrm... I triggered re-run on the windows break 3 times just to get more data. I have absolutely NO idea what that means...

**Comment by prestonvanloon** [comment]
Maybe something to do with the update in protoc. I didn't test anything for windows :(

**Comment by achew22** [comment]
Yeah, I don't really know what to do here. I don't have a windows box to test on. @jayconrod do you have a windows box for debugging?

**Comment by jayconrod** [comment]
I think this is protocolbuffers/protobuf#8049: protoc 3.14 doesn't build with MinGW on Windows.

We probably need to exclude this test on Windows in .bazelci/presubmit.yml (both in the `build` and `test`) sections. The other new targets can have `tags = ["manual"]` to prevent `//...` from matching them.

**Comment by achew22** [comment]
@jayconrod I've seen a couple of projects tag as `nowindows` and then put a test filter in their CI config. Is there a reason to exclude the target in the CI config over setting up a tag to handle this generically?

**Comment by jayconrod** [comment]
No strong opinion, but if a target fundamentally doesn't work on Windows (for example, if it tests `linkmode = "plugin"` which isn't supported on Windows), I think it's fine to tag the target itself with something that prevents it from being tested on Windows. If a target *should* work on Windows but doesn't due to some external issue, then I think we should (hopefully temporarily) disable it in CI.

At the moment, we basically don't have test coverage for `go_proto_library` on Windows, which is... not good. I hope we can fix that in the future and re-enable these tests.

**Comment by ah-edg** [comment]
This PR should no longer be required for field presence support since 3.15 (where "optional" is enabled by default).
It still looks like a sensible addition. The recently released [protoc 3.15.1](https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.1) contains the Windows build fix, might help with the CI without disabling tests on Windows...

**Comment by prestonvanloon** [comment]
@ah-edg Excellent! Let's close this. Users of proto3 optional can update to protoc 3.5.0 or later.

**Comment by prestonvanloon** [comment]
Just to clarify, I decided to close this since the experimental protoc flag was the use case to support this functionality. 
If anyone else has any use case for this feature, I would be happy to push it forward. However, I would not want to add this feature and it never be used.

**Pull request closed without merging**
