### PR TITLE
Data is not included transitively in dependant rules

### PR DESCRIPTION
**Pull request by achew22**
This is one part PR, one part issue.

As it says in the description, data is not pulled in transitively to targets. Could you help me understand what I need to do to this sample to make it work?

### CODE REVIEW

**Comment by pmbethe09** [comment]
Unlike Java, Go does not have a built-in way to embed resources in the compiled object.
AFAIK, people write custom code-generators to embed the resources in a .go file with a public variable/method for access.  So it makes no sense for data to be transitively inherited, as a go_binary would just ignore it.

We could do something similar in rules_go - a go_embed_data(...) rule, which takes one or more text files and makes a .go file with variables containing the text inside `` named by the file name (with some escaping of course).

**Comment by amlinux** [comment]
Sample code doesn't ask for embedding data in the binary. It marks data.txt as a runtime dependency that should be available to the binary when it runs.

**Comment by jayconrod** [comment]
@amlinux, that's correct, data.txt should be part of the runfiles, and it should be available to the test when it's run with "bazel test". I'm not sure yet why it isn't getting picked up. `runfiles` is a little underdocumented, so this may require digging into the Bazel source code.

**Comment by jayconrod** [comment]
This should be fixed in #324, so I'll close this. Let me know if anything is not working as expected.

**Pull request closed without merging**
