### PR TITLE
Added s390x support

### PR DESCRIPTION
**Pull request by kadamvandita**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by jayconrod** [comment]
Thanks for contributing this.

We just tagged release 0.7.1, which is our last release for Bazel 0.7. In the next few days, we'll replace our `config_setting` rules in `//platform` with rules that use platform-based constraint values. We'll also switch Gazelle to generate files for all the new `config_settings`. We'll make sure to include s390x in the list of platforms.

Once that work is done, I'll resolve merge conflicts on this PR. Basically the only thing that will be missing on master will be downloading the s390x toolchain. We don't have any way to check that it works, so I'll ask you to re-verify before merging.

**Comment by kadamvandita** [comment]
I have added code to download s390x toolchain and it is verified ,it works fine. 

Is there anything which needs to be re-verified from my end?

**Comment by kadamvandita** [comment]
Hi @jayconrod 

Should I work to resolve the confilts on the 2 branches?

- go/platform/BUILD.bazel

- go/tools/gazelle/config/platform.go

**Comment by jayconrod** [comment]
Ok, #1079 has landed, which was the patch we were waiting on. Sorry for the delay; the Travis CI Mac queue was very long yesterday, so we didn't get it merged until this morning.

I've fixed the merge conflicts. Please re-verify that it works.

**Comment by kadamvandita** [comment]
hi @jayconrod ,

I have verified the 2 commits, They work fine. They can be merged.

**Comment by jayconrod** [comment]
Jenkins test this please

**Comment by jayconrod** [comment]
Jenkins test this please

**Pull request merged**
