### PR TITLE
go_proto_library: drop dependencies on APIv1 WKT packages

### LINKED ISSUE #2721: go_proto_library: missing strict dependencies on WKTs with protoc 3.14
### What version of rules_go are you using?

v0.24.7

### What version of gazelle are you using?

n/a

### What version of Bazel are you using?

3.7.0

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

Darwin amd64

### What did you do?

Build pretty much any `go_proto_library` using protoc 3.14 or later.

For example:

```
bazel build @go_googleapis//google/api:annotations_go_proto

-- WORKSPACE --
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "207fad3e6689135c5d8713e5a17ba9d1290238f47b9ba545b63d9303406209c6",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.24.7/rules_go-v0.24.7.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.24.7/rules_go-v0.24.7.tar.gz",
    ],
)

http_archive(
    name = "com_google_protobuf",
    sha256 = "bf0e5070b4b99240183b29df78155eee335885e53a8af8683964579c214ad301",
    strip_prefix = "protobuf-3.14.0",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/v3.14.0.zip"],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

go_rules_dependencies()

go_register_toolchains()

protobuf_deps()
-- BUILD.bazel --
```

### What did you expect to see?

Successful build.

### What did you see instead?

```
ERROR: /private/var/tmp/_bazel_jayconrod/60e122df6a2a16ab6af86d77e9a71ec5/external/go_googleapis/google/api/BUILD.bazel:107:17: GoCompilePkg external/go_googleapis/google/api/annotations_go_proto.a failed (Exit 1): builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_amd64 -src ... (remaining 57 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_amd64 -src ... (remaining 57 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: missing strict dependencies:
	/private/var/tmp/_bazel_jayconrod/60e122df6a2a16ab6af86d77e9a71ec5/sandbox/darwin-sandbox/555/execroot/__main__/bazel-out/darwin-fastbuild/bin/external/go_googleapis/google/api/annotations_go_proto_/google.golang.org/genproto/googleapis/api/annotations/annotations.pb.go: import of "google.golang.org/protobuf/types/descriptorpb"
	/private/var/tmp/_bazel_jayconrod/60e122df6a2a16ab6af86d77e9a71ec5/sandbox/darwin-sandbox/555/execroot/__main__/bazel-out/darwin-fastbuild/bin/external/go_googleapis/google/api/annotations_go_proto_/google.golang.org/genproto/googleapis/api/annotations/client.pb.go: import of "google.golang.org/protobuf/types/descriptorpb"
	/private/var/tmp/_bazel_jayconrod/60e122df6a2a16ab6af86d77e9a71ec5/sandbox/darwin-sandbox/555/execroot/__main__/bazel-out/darwin-fastbuild/bin/external/go_googleapis/google/api/annotations_go_proto_/google.golang.org/genproto/googleapis/api/annotations/field_behavior.pb.go: import of "google.golang.org/protobuf/types/descriptorpb"
	/private/var/tmp/_bazel_jayconrod/60e122df6a2a16ab6af86d77e9a71ec5/sandbox/darwin-sandbox/555/execroot/__main__/bazel-out/darwin-fastbuild/bin/external/go_googleapis/google/api/annotations_go_proto_/google.golang.org/genproto/googleapis/api/annotations/resource.pb.go: import of "google.golang.org/protobuf/types/descriptorpb"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
bazel: Leaving directory `/private/var/tmp/_bazel_jayconrod/60e122df6a2a16ab6af86d77e9a71ec5/execroot/__main__/'
Target @go_googleapis//google/api:annotations_go_proto failed to build
```

### Analysis

From an email with @dsnet:

> This is almost certainly caused by the [`go_package` option in each .proto file being updated to reference the new Go protobuf module](https://github.com/protocolbuffers/protobuf/releases/tag/v3.14.0).
>
> Builds with the native Go toolchain will work fine since the tool knows how to resolve and obtain modules. However, the Bazel support for Go probably needs to be taught about these changed dependencies.
>
> In particular, the following packages have been "moved":
> "github.com/golang/protobuf/protoc-gen-go/descriptor" => "google.golang.org/protobuf/types/descriptorpb"
> "github.com/golang/protobuf/protoc-gen-go/plugin" => "google.golang.org/protobuf/types/pluginpb"
> "github.com/golang/protobuf/ptypes/any" => "google.golang.org/protobuf/types/known/anypb"
> "github.com/golang/protobuf/ptypes/duration" => "google.golang.org/protobuf/types/known/durationpb"
> "github.com/golang/protobuf/ptypes/empty" => "google.golang.org/protobuf/types/known/emptypb"
> "github.com/golang/protobuf/ptypes/struct" => "google.golang.org/protobuf/types/known/structpb"
> "github.com/golang/protobuf/ptypes/timestamp" => "google.golang.org/protobuf/types/known/timestamppb"
> "github.com/golang/protobuf/ptypes/wrappers" => "google.golang.org/protobuf/types/known/wrapperspb"
> "google.golang.org/genproto/protobuf/api" => "google.golang.org/protobuf/types/known/apipb"
> "google.golang.org/genproto/protobuf/field_mask" => "google.golang.org/protobuf/types/known/fieldmaskpb"
> "google.golang.org/genproto/protobuf/ptype" => "google.golang.org/protobuf/types/known/typepb"
> "google.golang.org/genproto/protobuf/source_context" => "google.golang.org/protobuf/types/known/sourcecontextpb"

### LINKED ISSUE #2741: Upgrade to protobuf 3.14.0 and drop implicit dependencies on APIv1 WKT packages
protobuf 3.14.0 will be the minimum supported version. The Well Known Types declare their Go paths to be in `google.golang.org/protobuf` (APIv2), rather than `github.com/golang/protobuf` (APIv1). This means newly generated code that imports those types will import packages from APIv2.

In #2739, we added implicit dependencies on both APIv1 and APIv2 packages to `go_proto_library`, since we don't know what version of protobuf is used during the loading or analysis phases. This means we'll compile both sets of packages, but we'll probably only import one.

### PR DESCRIPTION
**Pull request by jayconrod**
These should not be imported in generated code when protobuf 3.14 or
higher is used.

protobuf 3.14.0 will be the minimum supported version for rules_go 0.25.0.

For #2721
Fixes #2741

### CODE REVIEW

**Comment by jayconrod** [comment]
Blocked by protocolbuffers/protobuf#8049.

protoc 3.14.0 does not build on Windows with mingw64. I think this is a bug in protoc source, not mingw.

**Comment by vam-google** [comment]
@jayconrod Hi Jay! Google Ads is blocked by this. Can we by any chance prioritize this and merge it ASAP?

**Comment by jayconrod** [comment]
@vam-google It looks like protocolbuffers/protobuf#8049 is still open. I can't do anything until that's fixed. Forcing protobuf 3.14 would break Windows cgo users.

**Comment by steeve** [comment]
https://github.com/protocolbuffers/protobuf/commit/aee143afe8c17a3d2c7e88b70ffa6e08a73e2683 was merged 3 days ago, FYI

**Comment by achew22** [comment]
I think this is still blocked by a release of protoc that has it included. 3.15.0-rc1 doesn't have it, maybe 3.15.0 final will 
httpss://github.com/protocolbuffers/protobuf/releases

**Comment by prestonvanloon** [comment]
It's not mentioned in release notes, but v3.15.1 has https://github.com/protocolbuffers/protobuf/pull/8286 included

**Comment by akonradi** [comment]
What's next on this PR?

**Pull request merged**
