### PR TITLE
Move new runfiles library to `//go/runfiles`

### PR DESCRIPTION
**Pull request by fmeum**
Follows https://bazel.build/rules/deploying#runfiles_library.

### CODE REVIEW

**Comment by fmeum** [comment]
FYI @sluongng

**Comment by linzhp** [comment]
Since go/tools/bazel/runfiles is newly created and it's not released, why not moving the library to `go/runfiles`?

**Comment by achew22** [comment]
+1 let's move it instead of aliasing. The imports will be easier to work with as well

**Comment by fmeum** [comment]
Sounds good, will do. Should I keep the tests in the same Bazel package or move them to `tests`?

**Review by achew22 — APPROVED** [review]

**Comment by achew22** [comment]
Wrt tests that's dealers choice. I have a slight bias to move but don't mind

**Comment by fmeum** [comment]
@achew22 I moved the tests under `tests/`.

**Pull request merged**
