### PR TITLE
Fix .travis.yml

### PR DESCRIPTION
**Pull request by hochhaus**
Port from rules_closure repository with additional fixes

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by powelljo** [comment]
I'm not yet familiar with TravisCI but I tried to poke at this problem in #210.  From what I can tell, the same issue has arisen in your build against HEAD here too, i.e. the regexp being used is very forgiving and has picked up an invalid URL.

**Comment by hochhaus** [comment]
@powelljo Thanks. Working on a fix now.

**Comment by pmbethe09** [comment]
Jenkins, test this please.

**Pull request merged**
