### PR TITLE
protoc: create trivial files for missing outputs

### PR DESCRIPTION
**Pull request by jayconrod**
The grpc_gateway plugin only creates output files for .proto files
that includes service definitions. We still need to declare output .go
files, since we don't know which .proto files have services during
analysis, but we don't need to report errors.

Related #1388

### CODE REVIEW

**Comment by kellycampbell** [comment]
How will this tell the difference between a file that the plugin doesn't generate vs. a real failure where the file didn't get generated?

**Comment by jayconrod** [comment]
I'm assuming protoc will exit with a non-zero status if there's a failure in a plugin. Our protoc wrapper detects that and will also exit with a non-zero status.

**Comment by kaoet** [comment]
Does it fix https://github.com/bazelbuild/rules_go/issues/1309 ?

**Comment by jayconrod** [comment]
@kaoet Yes I think that's the same issue.

**Pull request merged**
