### PR TITLE
Preparing v0.32.0 release

### PR DESCRIPTION
**Pull request by linzhp**
This release brings many exciting changes

# New features
* `gomock` rule is officially supported in rules_go ([doc](https://github.com/bazelbuild/rules_go/blob/master/docs/go/extras/extras.md#gomock)), replacing the original jmhodges/bazel_gomock repository. Thanks to @jmhodges for the original implementation.
* rules_go now generates coverage reports in LCOV format by default (#3117), to be compatible with Bazel's `--combined_report=lcov`. To generate reports in the old `go tool cover` format, please use `--//go/config:cover_format=go_cover`. Thanks to @fmeum  
* supporting windows/arm64 (#3072). Thanks to @nsait-linaro 
* nogo config can now takes analyzer_flags (#3082), thanks to @NavneethJayendran 

# Bug fixes
* Consider volatile and stable status files separately (#3079) Thanks to @siddharthab
* Reducing duplicate information passed by go_pkg_info_aspect (#3111)
* Fix include paths for CGo deps in external repositories (#3115) thanks to @fmeum 
* Revert change to use resolved shared lib links (#2907), thanks to @glukasiknuro 
* Fix lost x_defs on test execution (#3135), thanks to @bozaro 
* Let go_binary's executable bit depend on linkmode (#3143) thanks to @fmeum 

# Deprecations
`go_embed_data` and `bindata` will be deprecated in rules_go 0.35.0. Users are encourage to migrate to `go:embed` and `embedsrcs`.

# Other changes
* Use output dir for empty packages to be hermetic (#3098), thanks to @joeljeske
* Prevent downgrading platforms (#3076), thanks to @cpsauer 
* Doc improvements (#3100), thanks to @sluongng 
* Remove legacy proto code for Bazel < 0.21 (#3099), thanks to @cpsauer 
* Remove unused coverage code (#3118), thanks to @fmeum 
* Moving tests for go_embed_data and gomock to tests/extras (#3122)
* Add command line copts/cxxopts to Cgo compile flags (#3126), thanks to @dchen496 
* Reset Go settings for protoc dependencies (#3005), thanks to @fmeum 
* Trim transitioned Go settings on non-Go dependencies (#3108), thanks to @fmeum 
# Updated dependencies
As always, you can use higher versions of rules_go's dependencies by declaring
them in WORKSPACE before calling go_rules_dependencies. Lower versions may
work but are not supported.
* `org_golang_google_protobuf` updated to v1.28.0
* `org_golang_x_sys`, `org_golang_x_xerrors`, `org_golang_google_genproto` and `go_googleapis` updated to `master`, as of 2022-05-09

### CODE REVIEW

**Comment by linzhp** [comment]
Many tests in Uber's Go monorepo failed due to #3117. I will hold this release.

**Comment by fmeum** [comment]
A hack defeats a hack, I guess. :-)
I think we could override the `SetPanicOnExit` function to not actually enable the feature, but still get the callback to be called. But then the feature is also quite useful, if it weren't for this trick.

**Comment by fmeum** [comment]
We should be able to disable the "panic on os.Exit(0)" feature, but still keep the hook, by removing this line: https://github.com/bazelbuild/rules_go/blob/fee2095e0a8219c93206be0b5adecfce6f32eac0/go/tools/bzltestutil/lcov.go#L174

@linzhp How would you feel about defaulting the feature to "on", as it is with the non-Bazel Go toolchain, and offering a knob to disable it, either globally via a config setting or an attribute on `go_test`?

**Comment by linzhp** [comment]
I have preparing a PR to restore panic on exit0 after we call `lcovAtExitHook()`

**Comment by linzhp** [comment]
Our team at Uber is planning to work on that this incoming sprint, but it won't make it to this release, which is already packed with features and fixes

**Pull request merged**
