### PR TITLE
Upgrade org_golang_x_tools to 0.5.0

### PR DESCRIPTION
**Pull request by linzhp**
org_golang_x_tools moved some packages and change the API for internal/facts package. Most notably, `internal/lsp` has been moved to the gopls module, so it's no longer part of `org_golang_x_tools`. As a result, `tests/integration/popular_repos/popular_repos.py` has to be updated.

### CODE REVIEW

**Review by fmeum — APPROVED** [review]
Looks good to me, but do you know why the line count went up by so much?

**Comment by robfig** [comment]
Ditto - a deletegopls patch with 113,709 additions, 9,500 deletions seems weird - why so many additions if it's deleting gopls?

**Comment by linzhp** [comment]
They moved the whole `internal/lsp` directory into `gopls`. So there are more code in `gopls` to delete now.

BTW, I am planning to exclude this PR from the 0.36.0 release to minimize the disruption, because this release already include so many changes. So don't merge this for now.

**Comment by uhthomas** [comment]
@linzhp Hey, we're hitting a bit of a wall at the moment where some packages require a version of golang.org/x/tools >= 0.3.0. Should we update this PR for 0.4.0 and try to merge it?

**Comment by linzhp** [comment]
`golang.org/x/tools >= 0.3.0` means 0.3.0 is OK, right?

I am planning to release a new version of Gazelle soon (see my recent Gazelle PRs), which is needed to properly upgrade golang/x/tools in rules_go, then merge this PR and release another version of rules_go.

**Comment by uhthomas** [comment]
Honestly, I'm not sure. We may actually require 0.4.0. What is blocking rules_go and Gazelle from using the newer version of golang.org/x/tools? Anything I can do to help?

**Comment by linzhp** [comment]
I can give 0.4.0 a try and let you know. I was just worried that 0.4.0 might bring more breaking changes on top of 0.3.0, so I try to move a small step at a time.

**Comment by linzhp** [comment]
@uhthomas I ran into some strange error with `org_golang_x_crypto`. Let me keep 0.3.0 in this PR for now. Feel free to open another PR for 0.4.0

**Comment by uhthomas** [comment]
No worries, it seems like a good idea to get this merged and then go for 0.4.0.

**Comment by linzhp** [comment]
OK, fixed all the issues. We are able to upgrade straight to 0.5.0

**Pull request merged**
