### PR TITLE
Gazelle: initial support for generalized directive comments

### PR DESCRIPTION
**Pull request by jayconrod**
Added config.ParseDirectives, which looks for comments of the form

    # gazelle:key value

Directives related to the configuration will be applied to a copy of
the current configuration, which is returned. This is passed down
through subdirectories by packages.Walk.

A full list of directives is returned. These may be processed by other
packages, for example gazelle:ignore and gazelle:exclude.

### CODE REVIEW

**Comment by jayconrod** [comment]
That's a good point. We should disallow directives that modify the configuration after the first rule for clarity.

I don't think we should do this for non-configuration directives though. I expect in the future there may be some that act as annotations on specific rules. `# keep` is already kind of like that. There are also things like `# gazelle:ignore` and `# gazelle:exclude` that clearly aren't rule-specific.

**Comment by jayconrod** [comment]
Ok, I've been experimenting with this a bit. Trying to find something reasonable without being too complicated. Here's what I'm thinking:

* There will be two kinds of directives: top-level, and annotation (this change will only support top-level, but I'm expected that annotations will be needed in the future).
* Top-level directives apply to the whole package. Things like `prefix` and `build_tags`. These must be written before the first statement (including `load`).
* Annotation directives may be written above rules. They affect process of the rule they annotate.
* This file will have a list of all valid directives and which kind they are. It will print an error message about any unknown directives or anything that's out of place.

WDYT?

**Comment by ianthehat** [comment]
Sounds good.

**Comment by achew22** [comment]
Will annotations be able to apply to individual lines like in a srcs attribute having `# gazelle:keep` in

```
go_library(
    name = "demo",
    srcs = [
        "main.go", # gazelle:keep
    ],
)
```

The example is admittedly contrived since main.go would be trivial to detect, but you get the idea.

**Comment by jayconrod** [comment]
@achew22 I'm not sure. Can you think of any uses? `# keep` will continue being supported, but it won't be processed by this module. That won't change.

There are some cosmetic directives supported by buildifier, like `keep sorted`, `do not sort`, and `buildifier: leave-alone`. I don't think Gazelle respects these, but we probably should. I can't think of others at the moment, but there are probably some.

**Comment by jayconrod** [comment]
@ianthehat I've implemented checking for top-level directives. I also split `ParseDirectives` into a function that extracts directives (which these checks) and a separate function that applies them to the `Config`. PTAL.

**Comment by achew22** [comment]
I just wanted to make sure that `# keep` still works. Thanks for taking input and being so open in your designs!

**Pull request merged**
