### PR TITLE
Fix gazelle asm files

### PR DESCRIPTION
**Pull request by sayrer**
I ran into this issue trying to run gazelle on golang.org/x/sys/unix

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by sayrer** [comment]
@yugui @pmbethe09 not sure who should look at this

**Comment by pmbethe09** [comment]
LGTM, ok by you @yugui

**Comment by yugui** [comment]
LGTM.
Jenkins, test this please.

**Comment by yugui** [comment]
Thank you for your contribution!

**Pull request merged**
