### PR TITLE
Fix library attr implementation for tests.

### LINKED ISSUE #6: go_test attr.library intentions
Imagine the dependency tree
`//libtwo:lib_test -> //libtwo:go_default_library ->  lib:go_default_library`
does the `library` attribute mean `deps` of the `library` should get pulled in automatically? I assume it is supposed to do that and thats why im reporting here.

repro: https://github.com/limdi/testing_go
```
bazel test ...
....
INFO: Found 4 targets and 1 test target...
ERROR: /home/limdi/testing_go2/libtwo/BUILD:17:1: error executing shell command: 'rm -rf bazel-out/local_linux-fastbuild/bin/libtwo/lib_test.dir && mkdir -p bazel-out/local_linux-fastbuild/bin/libtwo/lib_test.dir && mkdir -p bazel-out/local_linux-fastbuild/bin/libtwo/lib_test.di...' failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/home/limdi/.cache/bazel/_bazel_limdi/5dab422ce9814d504334f8f2f353d0aa/testing_go2/external/golang_linux_amd64/go/pkg/tool/linux_amd64/link: cannot open file /home/limdi/.cache/bazel/_bazel_limdi/5dab422ce9814d504334f8f2f353d0aa/testing_go2/external/golang_linux_amd64/go/pkg/linux_amd64/github.com/limdi/testing_go/lib/go_default_library.a: open /home/limdi/.cache/bazel/_bazel_limdi/5dab422ce9814d504334f8f2f353d0aa/testing_go2/external/golang_linux_amd64/go/pkg/linux_amd64/github.com/limdi/testing_go/lib/go_default_library.a: no such file or directory
INFO: Elapsed time: 981.661s, Critical Path: 0.69s

Executed 0 out of 1 tests: 1 fails to build.
```

My workaround: https://github.com/Limdi/rules_go/commit/f7b0346e1eb9506afc6cd715fa0f325c66b26f77

### PR DESCRIPTION
**Pull request by swsnider**
This was broken when the referenced library had transitive deps.

Fixes #6.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by swsnider** [comment]
If I should be pushing to a gerrit instance instead, please let me know.

**Comment by yugui** [comment]
Thank you for your contribution.  It looks good to me, but I think #31 and #33 are clearer as a solution.

**Comment by swsnider** [comment]
I agree -- I'll close this one.

**Pull request closed without merging**
