### PR TITLE
Handle relative import paths.

### PR DESCRIPTION
**Pull request by melindalu**
We ran into a problem with imports using relative paths to reference packages in the same repository of the form "../othersubpackage". @yugui @pmbethe09 does this look reasonable?

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by melindalu** [comment]
`I signed it!`

**Comment by yugui** [comment]
@melindalu 
LGTM, but could you name the importpath `lib/relativeimporter` or just `lib/relative` instead of`lib/relative_importer` to avoid underscore character?

Jenkins, test this please.

**Comment by melindalu** [comment]
@yugui good point, thanks — changed.

**Comment by pmbethe09** [comment]
LGTM

**Pull request merged**
