### PR TITLE
v0.30.0: update README

### PR DESCRIPTION
**Pull request by JamyDev**
Updates README.md for 0.30.0 release.

### CODE REVIEW

**Comment by linzhp** [comment]
@aiuto Can you help us copy the [released archive](https://github.com/bazelbuild/rules_go/releases/download/v0.30.0/rules_go-v0.30.0.zip) to https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.30.0/rules_go-v0.30.0.zip?

**Comment by JamyDev** [comment]
As well as the following archives that have changed:

- https://github.com/golang/sys/archive/da31bd327af904dd4721b4eefa7c505bb3afd214.zip -> https://mirror.bazel.build/github.com/golang/sys/archive/da31bd327af904dd4721b4eefa7c505bb3afd214.zip
- https://github.com/googleapis/go-genproto/archive/00ab72f36ad551e26984e123374ceffe52cff70b.zip -> https://mirror.bazel.build/github.com/googleapis/go-genproto/archive/00ab72f36ad551e26984e123374ceffe52cff70b.zip
- https://github.com/googleapis/googleapis/archive/d12b615374583712e7832c914d1fbef8c507f10f.zip -> https://mirror.bazel.build/github.com/googleapis/googleapis/archive/d12b615374583712e7832c914d1fbef8c507f10f.zip
- https://github.com/golang/tools/archive/v0.1.8.zip -> https://mirror.bazel.build/github.com/golang/tools/archive/v0.1.8.zip

**Comment by aiuto** [comment]
I mirrored https://github.com/bazelbuild/rules_go/releases/download/v0.30.0/rules_go-v0.30.0.zip

What are the other files?  They look like things which rules_go needs. Why are they not mirrored by the people who own them?

**Comment by aiuto** [comment]
It turns out we have been mirroring these in the past, so lets continue for now.
All should be done.

**Comment by JamyDev** [comment]
@aiuto the upgrade script would upload those, but since I don't have access I had to run it without the uploads. There are fallback paths of course, but we should still upload them. I'll make a task to write an uploader for binaries that haven't yet been uploaded so it's less manual.

**Pull request merged**
