### PR TITLE
Allow specification of alternate gRPC deps

### LINKED ISSUE #442: Allow vendored dependencies for `go_proto_library`
As it stands, whenever `go_proto_repositories()` is invoked it automatically adds `new_go_repository` entries for `org_golang_x_net` and `org_golang_google_grpc`, regardless of if they exist or not yet.  The `go_proto_library` rule also adds dependencies on `@org_golang_x_net//context:go_default_library` and `@org_golang_google_grpc//:go_default_library` (if the proto has servies) and `@com_github_golang_protobuf//proto:go_default_library` even if it doesn't.

If the project using these rules has vendored `golang.org/x/net` or `google.golang.org/grpc` this can create version clashing which will cause compilation to fail due to conflicting object files or conflicting definitions during build.

I think allowing for overriding the dependency paths just like the rules allows overriding protoc and protoc_gen_go would allow for more flexibility for users.

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #442 

Have tested this and it seem to work, but this is my first skylark, so be kind!

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by pmbethe09** [comment]
I saw https://github.com/bazelbuild/rules_go/pull/488 first -- should we go with that one?

**Comment by tomwilkie** [comment]
Yeah no problem!

**Comment by jayconrod** [comment]
Thanks for sending this! I'll close it though since #488 landed first.

**Pull request closed without merging**
