### PR TITLE
Typo --test_runner_fail_fast

### PR DESCRIPTION
**Pull request by Clement-Jean**
The real command argument is `--test_runner_fail_fast` not `--test_runner_fast_fast`

**What type of PR is this?**

> Documentation

**What does this PR do? Why is it needed?**

It corrects a typo in the documentation. The real command argument is `--test_runner_fail_fast` not `--test_runner_fast_fast`.

### CODE REVIEW

**Comment by fmeum** [comment]
Looks good, but please fix the failures by updating the docs with the commands included in the error messages.

**Comment by Clement-Jean** [comment]
@fmeum anything else I should do?

**Comment by fmeum** [comment]
@Clement-Jean It looks like the PR is now empty. You probably  have to update the source instead (in this case, I think, the Stardoc on `go_test`), which will then update the `.md` file.

**Comment by Clement-Jean** [comment]
@fmeum my bad, this is the first time i contribute to this project. Thank you for the guidance.

**Review by fmeum — APPROVED** [review]

**Pull request merged**
