### PR TITLE
added 'gofmt' to 'stdlib'

### PR DESCRIPTION
**Pull request by excavador**
I my skylark rules I need "gofmt" tool.
It different from "go fmt" (with space): accept more options

If I made it wrond or not optimal, please guide me, how to better integrate "gofmt" to rules_go

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by jayconrod** [comment]
Jenkins test this please

**Comment by jayconrod** [comment]
@ianthehat Is refactoring a lot of stuff around here right now. Not sure if this will conflict with any pending changes or not.

**Comment by excavador** [comment]
@jayconrod for me is any way to access to gofmt would be good.

"go fmt" unfortunatelly has some predefined hardcoded options.
for some tasks, like "check format of code on pre-commit hook" or "format my code" ("run" targets) I need to access to "gofmt" ("go fmt" will not solve my problems).

If you guide me some better way for that -  I would be happy to re-do my patch.
So, before it works, because golang directory and goroot were exposed completely, but as far as I can understand from the actual rules_go code, you construct own clean "bin" with only allowed tools.

There is reason why I made this patch.

**Comment by ianthehat** [comment]
You should not need this.
gofmt does not need to go in the stdlib, as it does not vary by build mode and does not get used in the build. You can just get it straight from the sdk, where it is already globbed and exposed as `@go_sdk//:bin/gofmt`

**Comment by excavador** [comment]
@ianthehat could you explain, how to use it?
https://gist.github.com/excavador/a6bfb227fcfd1cc7e7e5a07355ab6669

**Comment by ianthehat** [comment]
Your _gofmt attribute is wrong, you forgot to tag it as allow_single_file

**Comment by excavador** [comment]
@ianthehat another problem
```
external/go_sdk/bin/gofmt: cannot open `external/go_sdk/bin/gofmt' (No such file or directory)
external/go_sdk/bin/gofmt -l -w exe lib
```

**Comment by excavador** [comment]
Oh no, ploblem is solved. Wrong cwd was.

Thank you! You can reject the PR

**Pull request closed without merging**
