### PR TITLE
Add cpp flags to stdlib rule.

### LINKED ISSUE #985: cpp fragment options don't seem to be used during stdlib compilation
https://github.com/bazelbuild/rules_go/blob/f08376e2826201ad8dfe664b07b564262f79ecf4/go/private/rules/stdlib.bzl#L103

But they're exported on the line linked to above. Is this intended?

If these options are accidentally not wired to CGO_CXXFLAGS, etc. then I believe that using them *and* ensuring they include -fPIC is needed to make it possible to use go's c-shared buildmode. I say this because I reimplemented most of this logic by hand before realizing that this may be the problematic line.

### PR DESCRIPTION
**Pull request by nathantchan**
This change adds the flags from cpp fragments as environment variables
to the go install command.

Fixes #985

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by jayconrod** [comment]
cc @calpeyser

**Comment by jayconrod** [comment]
Jenkins test this please

**Comment by nathantchan** [comment]
Hmm...looks like I need to strip out some more flags.

**Comment by jayconrod** [comment]
Jenkins test this please

**Comment by jayconrod** [comment]
Manually verified this is passing on my Mac. Jenkins is being flaky.

**Pull request merged**
