### PR TITLE
Add iOS toolchains, platforms, and constraint_values

### LINKED ISSUE #2079: Bazel 0.26 break iOS and perhaps Android cross compilation
### What version of rules_go are you using?

```
ddea1ade19b0f7cab64d859d95fa6494714019d7
```

### What version of gazelle are you using?

```
325c4cf53b65148f5392f5f65462970a7e5cb6fa
```

### What version of Bazel are you using?

```
Build label: 0.26.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue May 28 08:38:24 2019 (1559032704)
Build timestamp: 1559032704
Build timestamp as int: 1559032704
```

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

```
Darwin XXXX 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```

### The problem

Bazel 0.26 ships with new platform enabled toolchains, which are defined like this:
```python
OSX_TOOLS_CONSTRAINTS = {
    "darwin_x86_64": ["@bazel_tools//platforms:osx", "@bazel_tools//platforms:x86_64"],
    "ios_i386": ["@bazel_tools//platforms:ios", "@bazel_tools//platforms:x86_32"],
    "ios_x86_64": ["@bazel_tools//platforms:ios", "@bazel_tools//platforms:x86_64"],
    "watchos_i386": ["@bazel_tools//platforms:ios", "@bazel_tools//platforms:x86_32"],
    "watchos_x86_64": ["@bazel_tools//platforms:ios", "@bazel_tools//platforms:x86_64"],
    "tvos_x86_64": ["@bazel_tools//platforms:ios", "@bazel_tools//platforms:x86_64"],
    "armeabi-v7a": ["@bazel_tools//platforms:arm"],
    "ios_armv7": ["@bazel_tools//platforms:ios", "@bazel_tools//platforms:arm"],
    "ios_arm64": ["@bazel_tools//platforms:ios", "@bazel_tools//platforms:arm"],
    "ios_arm64e": ["@bazel_tools//platforms:ios", "@bazel_tools//platforms:arm"],
    "watchos_armv7k": ["@bazel_tools//platforms:ios", "@bazel_tools//platforms:arm"],
    "watchos_arm64_32": ["@bazel_tools//platforms:ios", "@bazel_tools//platforms:arm"],
    "tvos_arm64": ["@bazel_tools//platforms:ios", "@bazel_tools//platforms:arm"],
}
```

Rules go uses the following constraints:
```python
GOOS = {
    "android": None,
    "darwin": "@bazel_tools//platforms:osx",
    "dragonfly": None,
    "freebsd": "@bazel_tools//platforms:freebsd",
    "linux": "@bazel_tools//platforms:linux",
    "nacl": None,
    "netbsd": None,
    "openbsd": None,
    "plan9": None,
    "solaris": None,
    "windows": "@bazel_tools//platforms:windows",
    "js": None,
}

GOARCH = {
    "386": "@bazel_tools//platforms:x86_32",
    "amd64": "@bazel_tools//platforms:x86_64",
    "amd64p32": None,
    "arm": "@bazel_tools//platforms:arm",
    "arm64": "@bazel_tools//platforms:aarch64",
    "mips": None,
    "mips64": None,
    "mips64le": None,
    "mipsle": None,
    "ppc64": None,
    "ppc64le": "@bazel_tools//platforms:ppc",
    "s390x": "@bazel_tools//platforms:s390x",
    "wasm": None,
}
```

Now the problem is that it then becomes impossible to build for iOS since the toolchain requires `@bazel_tools//platforms:ios` and `@bazel_tools//platforms:arm` but compiling for `darwin_arm64` requires/enforces `@bazel_tools//platforms:osx` and `@bazel_tools//platforms:aarch64`.

I'm not sure what to do here since we can't apply both `osx` and `ios` constraints on the same `constaint_setting`.

### PR DESCRIPTION
**Pull request by jayconrod**
Refactored the description of target platforms. The source of truth is
now the PLATFORMS table go/private/platforms.bzl. Declarations for
config_settings in //go/platform; constraint_values and aliases in
//go/toolchain; and toolchains in @go_sdk are generated from this
table.

In addition to the normal GOOS_GOARCH list, there are some additional
entries for iOS. iOS platforms still have GOOS=darwin, but they are
compatible with a different constraint_value
(@bazel_tools//platforms:ios instead of @bazel_tools//platforms:osx).

Fixes #2079

### CODE REVIEW

**Comment by jayconrod** [comment]
@steeve Please take a look. This should make it possible to `bazel build --platforms=@io_bazel_rules_go//go/toolchain:ios_arm`.

This is incomplete. I don't have a solution for `select` yet. Although it seems to compile correctly, it won't link (but my toolchain is probably just messed up).

**Comment by jayconrod** [comment]
I added a commit that should fix `@io_bazel_rules_go//go/platform:darwin`. It should be true if target platform is any Go `darwin` or `ios` platform or if the target platform is the default (not cross-compiling) and the host OS is macOS.

**Comment by steeve** [comment]
@jayconrod it seems I can't use the `@io_bazel_rules_go//go/toolchain:ios` with your patch. I suspect only the `os_arch` combination exist ?

**Comment by steeve** [comment]
I tried constraining on `@bazel_tools//platforms:ios`, and I'm happy to report that it works!

**Comment by steeve** [comment]
Now I'm having issues on Android:
With `android_arm64`:
```
ERROR: While resolving toolchains for target //android/java/main:ZenlyCore: no matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type
ERROR: Analysis of target '//android:publish_snapshot' failed; build aborted: no matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type
```

I suspect this is a problem in the NDK rules of Bazel.

And on `android_arm`:
```
ERROR: /private/var/tmp/_bazel_steeve/309ac22c92b055a3e3f78825fe63406b/external/org_golang_google_grpc/internal/syscall/BUILD.bazel:3:1: Illegal ambiguous match on configurable attribute "deps" in @org_golang_google_grpc//internal/syscall:go_default_library:
@io_bazel_rules_go//go/platform:android
@io_bazel_rules_go//go/platform:darwin
Multiple matches are not allowed unless one is unambiguously more specialized.
INFO: SHA256 (http://jcenter.bintray.com/org/ow2/asm/asm/6.2/asm-6.2.jar) = 917bda888bc543187325d5fbc1034207eed152574ef78df1734ca0aee40b7fc8
ERROR: Analysis of target '//android:publish_snapshot' failed; build aborted:

/private/var/tmp/_bazel_steeve/309ac22c92b055a3e3f78825fe63406b/external/org_golang_google_grpc/internal/syscall/BUILD.bazel:3:1: Illegal ambiguous match on configurable attribute "deps" in @org_golang_google_grpc//internal/syscall:go_default_library:
@io_bazel_rules_go//go/platform:android
@io_bazel_rules_go//go/platform:darwin
Multiple matches are not allowed unless one is unambiguously more specialized.
INFO: Elapsed time: 6.105s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (23 packages loaded, 8805 targets configured)
```

**Comment by steeve** [comment]
Note that this happens also on bazel 0.25.3
`android_arm`
```
/private/var/tmp/_bazel_steeve/309ac22c92b055a3e3f78825fe63406b/external/org_golang_google_grpc/internal/channelz/BUILD.bazel:3:1: Illegal ambiguous match on configurable attribute "deps" in @org_golang_google_grpc//internal/channelz:go_default_library:
@io_bazel_rules_go//go/platform:darwin
@io_bazel_rules_go//go/platform:android
Multiple matches are not allowed unless one is unambiguously more specialized.
```

`android_arm64`:
```
/private/var/tmp/_bazel_steeve/309ac22c92b055a3e3f78825fe63406b/external/org_golang_google_grpc/internal/channelz/BUILD.bazel:3:1: Illegal ambiguous match on configurable attribute "deps" in @org_golang_google_grpc//internal/channelz:go_default_library:
@io_bazel_rules_go//go/platform:darwin
@io_bazel_rules_go//go/platform:android
Multiple matches are not allowed unless one is unambiguously more specialized.
```

**Comment by steeve** [comment]
cc @jin since he made the NDK rules
@jin could it be that the NDK rules suffered from the same bug from https://github.com/bazelbuild/bazel/pull/8522 ?

**Comment by steeve** [comment]
Hum this is weird, when I constrain on `@bazel_tools//platforms:aarch64` instead of `@io_bazel_rules_go//go/toolchain:arm64`, I get the same issue as `android_arm`.

**Comment by jayconrod** [comment]
> it seems I can't use the @io_bazel_rules_go//go/toolchain:ios constraint with your patch. I suspect only the os_arch combination exist ?
> The reason is we have our own platform that used to apply rules_go constraints

Some explanation about the naming here: `//go/platform` contains `config_setting` targets for each `GOOS`, `GOARCH`, and `GOOS_GOARCH` pair. `//go/toolchain` contains `constraint_setting`, `constraint_value`, and `platform` targets. Ideally `platform` targets would be in `//go/platform`, but that package predates Bazel support for platforms and toolchains by quite a bit, and displacing the old `config_settings` would break builds.

Anyway, you should be able to define a `platform` like this:

```
platform(
    name = "custom_ios_arm",
    constraint_values = [
        "@bazel_tools//platforms:ios",
        "@bazel_tools//platforms:arm',
        "@io_bazel_rules_go//go/toolchain:is_darwin",  # needed for @io_bazel_rules_go//platform:darwin to work
        # any other values relevant to your toolchains
    ],
)
```

I think the Android problems you're experiencing are #2089, which is affecting cross-compilation in general. I'm planning to fix that in another PR before the next release.

**Pull request merged**
