### PR TITLE
Set Xcode configuration only when building objc

### PR DESCRIPTION
**Pull request by siddharthab**
Resolves https://github.com/bazelbuild/rules_go/issues/1554.

@steeve Can you also take a look and see if this change works for you?

### CODE REVIEW

**Comment by steeve** [comment]
Unfortunately that won't work, since those configurations are needed across all build targets (`stdlib` even).
However, since I believe the issue is only on MacOS, we can try to disable it from being recognized as an Apple Platform needing configuration. Just remove it from https://github.com/bazelbuild/rules_go/blob/master/go/platform/apple.bzl#L26 and that may solve your problem.

That will prevent from accessing `apple_common.XcodeVersionConfig`.

**Comment by siddharthab** [comment]
Are you suggesting I disable it behind a feature flag? I.e. a flag on the command line stops the function from being called.

**Comment by steeve** [comment]
I meant try to comment out the line I mentioned, it will then ignore mac OS as an Apple platform.

**Comment by siddharthab** [comment]
Oh yes, that definitely works. And so does providing macos_sdk_version flag. I am trying to get a fix merged here so my organisation does not have to maintain its own fork.

**Comment by siddharthab** [comment]
I see. I updated the PR.

Will having objc code still work for macOS platform, or are we saying we should not support it?

**Comment by steeve** [comment]
It should still work, although you're right that needs testing.
These env vars are here for cc_library. I think objc_library will work fine, but that needs testing.

**Comment by jayconrod** [comment]
I'm not sure I fully understand the impact of this change. Will this break builds with C/C++/ObjC code on macOS?

**Comment by siddharthab** [comment]
I am not sure. @steeve says they should work, and the Travis tests pass. Is there some more testing I can do?

**Comment by jayconrod** [comment]
Travis and BuildKite all seem to be passing, but I doing think we have a CI configuration that tests macOS with only Xcode command line tools; I think all CI machines have Xcode installed.

On my laptop, I tried uninstalling Xcode and reinstalling just the command line tools. Builds that include objc fail with the same message with and without this change. Is that intentional, or is everything supposed to pass after this change?

**Comment by siddharthab** [comment]
Yes, I think Objective C definitely needs Xcode. We want to ensure two things with this change:

1. C/C++ builds continue to work without Xcode for macOS platform.
2. ObjC builds continue with with Xcode for macOS platform.

I think that Travis checked for condition 2, and you and I checked for condition 1. So we should be good now. 😄

**Comment by jayconrod** [comment]
I hope so :) I'm not familiar enough with ObjC and Xcode support in Bazel to be confident in this change, but it seems like it's working so...

**Pull request merged**
