### PR TITLE
Remove some fields from Go context

### PR DESCRIPTION
**Pull request by dzbarsky**
**What type of PR is this?**
Starlark cleanup

**What does this PR do? Why is it needed?**
All of these are either unused or can easily be retrieved from another context field.
We were already retrieving them from both so this change makes things more consistent.

**Which issues(s) does this PR fix?**

Fixes #

**Other notes for review**

### CODE REVIEW

**Comment by sluongng** [comment]
Im a bit iffy about this.

On one hand, this is a nice cleanup, probably overdue.

On the other hand, we have been advertising Go context wrapper as the canonical way to extend rules_go. I can see some downstream rules depending on `go_ctx.go` to access the binary directly for example.

Perhaps leaving the removed fields in the source as comments, each pointing to their replacement would help folks migrate more easily? WDYT?

**Comment by dzbarsky** [comment]
> Im a bit iffy about this.
> 
> On one hand, this is a nice cleanup, probably overdue.
> 
> On the other hand, we have been advertising Go context wrapper as the canonical way to extend rules_go. I can see some downstream rules depending on `go_ctx.go` to access the binary directly for example.
> 
> Perhaps leaving the removed fields in the source as comments, each pointing to their replacement would help folks migrate more easily? WDYT?

That's a good idea. If we want to avoid breakage, we can also add a deprecated_props kwarg or otherwise shim things so that internal rules get a slimmed down context and external world has a chance to migrate

**Comment by fmeum** [comment]
I'm also in favor of cleaning up rules_go's own usages while still providing the same props, but moved to a separate "deprecated" section in the docs. We can call out their imminent removal in the release notes.

**Comment by dzbarsky** [comment]
> I'm also in favor of cleaning up rules_go's own usages while still providing the same props, but moved to a separate "deprecated" section in the docs. We can call out their imminent removal in the release notes.

I've updated to allow opting out of deprecated properties and added to the docs. WDYT of this approach?

**Review by fmeum — APPROVED** [review]
This is great, thanks for simplifying the migration!

**Pull request merged**
