### PR TITLE
Support for Go 1.12.1

### PR DESCRIPTION
**Pull request by dims**
Change-Id: If8e706d3ea15684741a8355b74ccf2981d37f82b

### CODE REVIEW

**Comment by dims** [comment]
cc @jayconrod @ixdy

**Comment by jayconrod** [comment]
Thanks for sending this, but sorry, I don't accept PRs that add new Go versions, since it takes more time to verify these PRs than it does to prepare them.

I'll add support for 1.12.1 and tag new rules_go releases soon, likely tomorrow.

**Comment by dims** [comment]
@jayconrod ack on that. Some background, it's not a random request :)

We at Kubernetes have been waiting for a specific fix (sync.Once broken in 1.12) so we can test the upcoming 1.14 release of kubernetes (we have flaky/broken CI jobs because of the problem). Please see [1] for additional context

Thanks!

[1] https://github.com/kubernetes/kubernetes/issues/74890#issuecomment-472635718

**Comment by jayconrod** [comment]
FYI #1994 will add support for both 1.12.1 and 1.11.6. I'll cherry-pick these back to the last three release branches. rules_go 0.18.1, 0.17.2, and 0.16.8 will be out tomorrow (or maybe tonight if all goes well).

**Comment by dims** [comment]
Thanks a ton @jayconrod

**Pull request closed without merging**
