### PR TITLE
gazelle: Add ability to read/write to BUILD.bazel instead of BUILD

### PR DESCRIPTION
**Pull request by pmbethe09**
Start of fix for 
https://github.com/bazelbuild/rules_go/issues/144

After this, use it in new_go_repository.

### CODE REVIEW

**Comment by kyessenov** [comment]
Hi, can you merge this PR?
I'd like to use this fix.

**Comment by kyessenov** [comment]
How do we use this option from WORKSPACE? I'm trying to import golang.org/x/text...

**Comment by twpayne** [comment]
@kyessenov See #228 to how to use this from `WORKSPACE`.

**Comment by kyessenov** [comment]
I am using latest rules_go and I get "no such attribute 'build_file_name' in 'new_go_repository' rule."
It doesn't look like the field is defined in the rule.

**Comment by twpayne** [comment]
@kyessenov, that's because these PRs haven't been merged yet.

**Pull request merged**
