### PR TITLE
Arm64 support on Linux

### LINKED ISSUE #1506: arm64 support
As noted in https://github.com/lyft/protoc-gen-validate/issues/75#issuecomment-389946862 , the operating system automatic selection system at

https://github.com/bazelbuild/rules_go/blob/master/go/private/sdk.bzl#L29-L38

misidentifies an linux_arm64 system as linux_amd64 (because there is no case that properly matches the `uname -p` call). As it is written in that mentioned issue by @akonradi:

> The issue is that if repository_ctx.os.name is 'linux', there's no way to set the host as linux_arm64 - it defaults to linux_amd64. See
https://github.com/bazelbuild/rules_go/blob/3b103d6954cd4508e1f63c8e2ea57bda18d98bcf/go/private/sdk.bzl#L31-L37

### PR DESCRIPTION
**Pull request by ArielleA**
Arm64 support fixes #1506  requires pull request bazelbuild/bazel#5360

### CODE REVIEW

**Comment by steeve** [comment]
That one looks great, and might even make split configurations work when building ios and android multi arch targets.

**Comment by jayconrod** [comment]
Change looks good, but it's failing tests. Something about toolchains not being registered. I'll take a look today and figure out what's happening.

**Comment by ArielleA** [comment]
It's almost certainly because the cpu constraint isn't exported in bazel-tools/platform. That export is in my pull request #5360. Should I withdraw and resubmit once the dependant pull request is complete?

**Comment by jayconrod** [comment]
Ok, that makes sense.

Let's keep this PR open and wait until bazelbuild/bazel#5360 has been merged and released in a new version of Bazel. At that point, rebase to `master` and ping me to take another look. I'll update the minimum supported version of Bazel and merge this.

**Comment by jayconrod** [comment]
Bazel 0.15.0 is now released. I'd like to to one more major release of rule_go (likely early next week) before merging this PR and making Bazel 0.15.0 the minimum supported version.

**Comment by vielmetti** [comment]
The Bazel 0.15.0 release issue is here: https://github.com/bazelbuild/bazel/issues/5057 for reference.

**Comment by jayconrod** [comment]
I updated this PR to tip of `master`. It looks like the `aarch64` platform didn't actually make it into Bazel 0.15.0 (which is now the rules_go minimum supported version). I can confirm the build works with Bazel 0.16.0rc4 at least, but I can't make 0.16.0 the minimum version yet.

**Comment by vielmetti** [comment]
Thanks @jayconrod . What is the release cadence for Bazel? Trying to determine at what pace I need to track this to get these changes incorporated into projects up and downstream.

**Comment by jayconrod** [comment]
@vielmetti Bazel aims for a release every month, but they are quite late this month. You can track this month's release at bazelbuild/bazel#5058.

**Comment by jayconrod** [comment]
@lubinsz This breaks on Bazel 0.15, which is our minimum supported version.

I'm planning to tag a release of rules_go next week. We can bump the minimum supported Bazel version after that and then merge this.

**Comment by steeve** [comment]
This might need rebasing on master too

**Comment by ArielleA** [comment]
I'll rebase it once 0.17 is out, allow us to get some more issues with the Arm64 port resolved.

**Comment by lubinsz** [comment]
@ArielleA @jayconrod 
Can we merge it now?

**Comment by jayconrod** [comment]
@lubinsz Now that Bazel 0.17 is out, we should be fine. Merged.

**Comment by lubinsz** [comment]
@jayconrod 
Hi,
When will the new version be released with this patch in https://github.com/bazelbuild/rules_go/releases?
Thanks.

**Comment by jayconrod** [comment]
@lubinsz I expect we'll tag a major release this week.

**Pull request merged**
