### PR TITLE
Use `ctx.readdir` instead of `ls` for SDK platform detection

### LINKED ISSUE #2345: Failed to detect SDK platform on Windows 10
### What version of rules_go are you using?
0.21.0

### What version of gazelle are you using?
0.19.1

### What version of Bazel are you using?
Build label: 2.0.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 19 12:31:16 2019 (1576758676)
Build timestamp: 1576758676
Build timestamp as int: 1576758676

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
Windows 10, AMD64

### What did you do?
Tried using `go_host_sdk` with the path of my local Go SDK

### What did you expect to see?
`bazel build //...` should correctly build my Go targets

### What did you see instead?
```
ERROR: While resolving toolchains for target //lib/db:go_default_library: invalid registered toolchain '@go_sdk//:go_android_386': no such package '@go_sdk//': Traceback (most recent call last):
        File "C:/users/xxxx/_bazel_xxxx/7rcsayal/external/io_bazel_rules_go/go/private/sdk.bzl", line 41
                _detect_sdk_platform(ctx, <1 more arguments>)
        File "C:/users/xxxx/_bazel_xxxx/7rcsayal/external/io_bazel_rules_go/go/private/sdk.bzl", line 236, in _detect_sdk_platform
                fail(<1 more arguments>)
Could not detect SDK platform
```
Similar errors are thrown for `@go_sdk//:go_android_amd64` etc., all the toolchains that I did not register, or did not use in my source. Bazel only complains about the first invalid toolchain. When run again, the toolchain differs, but the complaint is the same.

### PR DESCRIPTION
**Pull request by fmeum**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

**Which issues(s) does this PR fix?**

Fixes #2345

**Other notes for review**

### CODE REVIEW

**Comment by fmeum** [comment]
@adam-azarchs Could you test whether this fixes https://github.com/bazelbuild/rules_go/issues/2345#issuecomment-1486291256 for you?

**Comment by adam-azarchs** [comment]
Yep, that seems to fix it, thanks!

(though this only gets me as far as running into a gazelle bug... one step at a time)

**Comment by fmeum** [comment]
Thanks for the confirmation. Feel free to ping me on the Gazelle issue.

**Comment by fmeum** [comment]
Thanks for the confirmation. Feel free to ping me on the Gazelle issue.

**Review by linzhp — APPROVED** [review]

**Pull request merged**
