### PR TITLE
When running gazelle with --mode=diff, show missing BUILD file path instead of /dev/null when it does not exist.

### PR DESCRIPTION
**Pull request by stefan-improbable**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by jayconrod** [comment]
Thanks for sending this! Looks good, pending CLA and CI.

Jenkins test this please.

**Comment by stefan-improbable** [comment]
I signed it!

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by stefan-improbable** [comment]
Thanks for merging!

**Comment by jayconrod** [comment]
Thanks for fixing this! :)

**Pull request merged**
