### PR TITLE
Update docs regarding vendored proto files

### PR DESCRIPTION
**Pull request by garymm**
**What type of PR is this?**

Documentation

**What does this PR do? Why is it needed?**

https://github.com/bazelbuild/bazel/issues/3867 is fixed, so
instructions for vendored proto files need to be updated.

### CODE REVIEW

**Comment by fmeum** [comment]
> proto_library is now provided by rules_proto, not built-in.

Which Bazel version contains this change?

**Comment by garymm** [comment]
@fmeum not sure. The docs [here](https://bazel.build/reference/be/protocol-buffer#proto_library) say:

> Deprecated. Please use https://github.com/bazelbuild/rules_proto instead.

**Comment by fmeum** [comment]
I think that `proto_library` is still part of Bazel. This deprecation was added since the long-term plan is to load `proto_library` from `rules_proto`. But that would require having everyone load it from `rules_proto` explicitly.

Could we split this PR in two parts? The other half seems completely non-controversial.

**Comment by garymm** [comment]
What is the objection to directing people to use the non-deprecated proto_library?

**Review by fmeum — APPROVED** [review]
Thanks!

**Pull request merged**
