### PR TITLE
proto: Add grpc-gateway compiler

### PR DESCRIPTION
**Pull request by ashi009**
Add grpc-gateway compiler in //proto (#992 and #1139).

This CL is a working prototype.  I'll add tests if this direction looks good.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by ashi009** [comment]
Rebased on the current master.   Will add an example later.

**Comment by ashi009** [comment]
I just realized that, writing a working example is very difficult.   `google/api` repo cannot imported directly as gazelle is not able to generate proper build file for those files.  There is also no repository hosting generated go files . So the only option would be writing a `new_http_repository` rule with a local build file, which is probably not a good idea to serve the purpose of an example -- as we don't really want all the users to do this for their own repository.

Another issue with this approach is that, gazelle won't be able to generate build file "correctly" for a service proto file with http annotations.  So I'll leave this out of the example for now.

With the latest progress in grpc-gateway repo that import_path is added but the CI is failing.  I've put a big TODO on top to remove the import_path_option from the compiler option once it's released.

**Comment by ianthehat** [comment]
My concern is that if this is added to this repository it becomes a rule I have to support, that other people will depend on, but I have no way to even run it, let alone check it works, so it will get broken.

**Comment by Globegitter** [comment]
@ashi009 Yeah it would be great to get an example. I was just trying to use this branch and also did not quite manage. Also grpc gateway 1.3.1 has now been released, making it possible to fix one of your todos.

**Comment by novabyte** [comment]
@ashi009 I've tried out the code on this pull request and have been unable to set it up either. The issue I believe is with how the "google/api/annotations.proto" and "google/api/http.proto" sources should be resolved. How were you able to make it work?

**Comment by ashi009** [comment]
@Globegitter: The blocker is with google/api repo and gazelle generating build file for multiple proto files in the same directory ATM. I'll double check them this week.

@novabyte: It's tricky, but do-able. One simple solution is to put `google/api/{annotations,http}.proto` in the `${workspace}/google/api` , and throw a hand crafted `BUILD` file in it.  ie.

```
# gazelle:ignore
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")

proto_library(
    name = "annotations_proto",
    srcs = [
        "annotations.proto",
        "http.proto",
    ],
    visibility = ["//visibility:public"],
    deps = ["@com_google_protobuf//:descriptor_proto"],
)

go_proto_library(
    name = "annotations_go_proto",
    importpath = "google.golang.org/genproto/googleapis/api/annotations",
    proto = ":annotations_proto",
    visibility = ["//visibility:public"],
    deps = ["@com_github_golang_protobuf//protoc-gen-go/descriptor:go_default_library"],
)

alias(
    name = "go_default_library",
    actual = "@org_golang_google_genproto//googleapis/api/annotations:go_default_library",
    visibility = ["//visibility:public"],
)
```

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by Globegitter** [comment]
I added 

```
BUILD_FILE_CONTENT = """
proto_library(
  name = 'annotations_proto', 
  srcs = ['google/api/annotations.proto'], 
  deps=[
    ':http_proto',
    '@com_google_protobuf//:descriptor_proto'
  ],
  visibility = ['//visibility:public'],
)
proto_library(
  name = 'http_proto', 
  srcs = ['google/api/http.proto'], 
  visibility = ['//visibility:public'],
)
"""

new_http_archive(
    name = "com_github_googleapis_googleapis",
    build_file_content = BUILD_FILE_CONTENT,
    strip_prefix = "googleapis-94ba270676352628895b3cbb8da12a8fd3dcb88a",
    sha256 = "27eacc432c26408ab103ac1a689fd93dea2a81015f901c669d10738963c43e07",
    url = "https://github.com/googleapis/googleapis/archive/94ba270676352628895b3cbb8da12a8fd3dcb88a.tar.gz",
)
```

and now got it to work with the latest commit. Next step is getting the swagger generation set up.

**Comment by Globegitter** [comment]
@ashi009 I know this is only partially related to this pr, but how do you get to generate the swagger documentations? Writing my own `go_proto_compiler` did not work. I could probably depend on `rules_protobuf` for this but would like to try and avoid that if possible.

**Comment by ashi009** [comment]
You won’t solve it with go_proto_compiler rule. As the swagger gen
generates json file instead of go source code.

The short answer would be writing your own skylark extension, creating a
new rule that depends on proto_library. It should be fairly simple to
achieve that, though the docs is not very comprehensive.

Note that you won’t be able to use proto aspect atm, as the comments in the
proto files are stripped out before passing into the swagger gen as proto
descriptor set. (I have filed a bug with bazel team for tracking that.)
Markus Padourek <notifications@github.com>于2018年1月12日 周五下午4:47写道：

**Comment by chaitanya9186** [comment]
When are we planning to merge this?

**Comment by jayconrod** [comment]
Closed per discussion in #1495.

**Pull request closed without merging**
