### PR TITLE
Try running the tests on Windows

### PR DESCRIPTION
**Pull request by philwo**

### CODE REVIEW

**Comment by jayconrod** [comment]
I wouldn't expect this to work at the moment, but we have a Q2 OKR for full Windows support.

**Comment by dwatley** [comment]
@jayconrod Is your timeline still accurate?

**Comment by jayconrod** [comment]
Yes, I still hope to have this working by the end of the quarter.

**Comment by jayconrod** [comment]
Closing in favor of #1791

**Pull request closed without merging**
