### PR TITLE
protoc: only present import_path when using protoc-gen-go

### PR DESCRIPTION
**Pull request by ashi009**
This is an attempt on fixing #1139, which makes it possible to add grpc-gateway protoc compiler.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by ianthehat** [comment]
#1165

**Comment by ianthehat** [comment]
#1165 was submitted and should make this PR redundant

**Comment by ashi009** [comment]
#1165 LGTM, dropping this one.

**Pull request closed without merging**
