### PR TITLE
Upgrade rules_cc to 7bd0e49cfb2237086df89dca9e6ba7a5a5dfb36d

### PR DESCRIPTION
**Pull request by achew22**
This is a part of https://github.com/bazelbuild/bazel-gazelle/pull/760.

To update the copy in the bazel mirror:

```
cd $(mktemp -d)
wget https://github.com/bazelbuild/rules_cc/archive/7bd0e49cfb2237086df89dca9e6ba7a5a5dfb36d.zip
gsutil cp 02becfef8bc97bda4f9bb64e153f1b0671aec4ba.zip gs://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/02becfef8bc97bda4f9bb64e153f1b0671aec4ba.zip
```

Fixed: #2711

### CODE REVIEW

**Comment by achew22** [comment]
Interestingly, it looks like the test is failing because of a minimum version issue. The missing keyword is flagged by `incompatible_use_toolchain_transition` which appeared in [`3.4`](https://blog.bazel.build/2020/07/13/bazel-3-4.html#rules) I know you don't bump minimum versions lightly, so I wanted to just point this out and see what you thought.

**Comment by jayconrod** [comment]
Is it important that this update happens now? I'll update everything for the `v0.25` release next month, and it's really much easier to update everything together. Gazelle should only use release versions, and I won't be able to backport this to a patch release.

**Comment by achew22** [comment]
> Is it important that this update happens now?

Sorry to make that unclear. It's totally okay to hold off on this. I was merely trying to

1. Get an item in the release TODO list
2. Make that item a single clock away for you

No rush. Thanks for being so prompt and wonderful 🙂

**Comment by jayconrod** [comment]
Cool, will hold off for now then. Thanks for working through this and for being patient. I know multi-stage changes over a long time are hard to deal with.

**Comment by UebelAndre** [comment]
With `v0.25` out does that mean the cc rules were updated?

**Comment by jayconrod** [comment]
@UebelAndre Yes. I'll close this PR since it's superseded by #2742.

**Pull request closed without merging**
