### PR TITLE
Remove deprecated rules

### PR DESCRIPTION
**Pull request by sluongng**
**What type of PR is this?**

> Uncomment one line below and remove others.

Other

**What does this PR do? Why is it needed?**

These rules should have been removed in 0.39 release but were not.

**Which issues(s) does this PR fix?**

Fixes #

**Other notes for review**

### CODE REVIEW

**Review by fmeum — APPROVED** [review]
Since 0.39.0 contained so many fixes and improvements for Bzlmod, we didn't want to tie it to the removals. 

I will hold onto merging this until the patch release is out.

**Review by linzhp — COMMENTED** [review]
Thanks for doing this, but can you give us a bit more time in removing bindata in Uber? @tyler-french is working on it.

**Comment by sluongng** [comment]
I don't think there is any rush in applying this patch. So if it takes a few days for Uber to sort out the bindata removal, then it should be fine.

Or if you want me to split the bindata removal into a separate PR to merge separately, do let me know.

**Comment by linzhp** [comment]
Let's wait and land this, so you don't need to do hair splitting

**Comment by sluongng** [comment]
@linzhp any update on this?

**Comment by linzhp** [comment]
@uberzzr is steadily making progress in the internal migration

**Review by linzhp — APPROVED** [review]
We are done with the migration. Thanks for the patience

**Comment by sluongng** [comment]
There seem to be some network flake that affected auto merge here. Please try again 🙏

**Comment by fmeum** [comment]
@sluongng The link variant of the path test is still failing. Could you send a separate PR to disable it? We know it's unsound.

**Comment by sluongng** [comment]
Yup, reasonable https://github.com/bazelbuild/rules_go/pull/3559

**Comment by sluongng** [comment]
@fmeum I rebased this PR on top of master. We should get it merged this time considering the `go_path` issue has been side stepped. 🤗

**Comment by linzhp** [comment]
That's my thought too

**Comment by fmeum** [comment]
@linzhp I will merge this now that 0.41.0 is out.

**Pull request merged**
