### PR TITLE
Fix coverage collection with modified `COVERAGE_DIR` env variable

### LINKED ISSUE #3819: Coverage is not working if `os` module is used in test
While running coverage on a pkg that use the `os` module, coverage is not outputed. 

### What version of rules_go are you using?
0.44.2

### What version of gazelle are you using?
0.35.0

### What version of Bazel are you using?
7.0.0

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
Darwin / arm64

### What did you do?
Please see this repository for reproduction:
https://github.com/supercairos/bazelgoperfectcoverage

running 
`bazel coverage //...` don't produce any coverage. 

### What did you expect to see?
Some coverage produced

### What did you see instead?
No coverage produced

### PR DESCRIPTION
**Pull request by fmeum**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

**Which issues(s) does this PR fix?**

Fixes #3819 

**Other notes for review**

### CODE REVIEW

**Comment by fmeum** [comment]
I tried to add a test for this, but it failed with race detection, presumably because `os.Clearenv` is prone to races. I verified manually that this fixes the issue.

**Review by linzhp — APPROVED** [review]
Maybe you can turn the race detection off for this test?

**Comment by fmeum** [comment]
Found a way to do this by using `Setenv` for the same purpose.

**Review by linzhp — APPROVED** [review]
Nice

**Pull request merged**
