### PR TITLE
Simplify symlink handling

### PR DESCRIPTION
**Pull request by jayconrod**
* Introduced _relative_path_from_dir which calculates the relative path
  from a directory to a file.
* Rewrote _symlink_tree_commands (now private) using this new function.
* Removed _remove_external_prefix and _is_external. They were no-ops
  since Bazel no longer expresses external paths as "../repo".
* Simplified path munging in compile and link actions and fixed
  quoting in a few places.

### CODE REVIEW

**Comment by jayconrod** [comment]
Tests are failing because of #361. I'll fix that first.

**Comment by jayconrod** [comment]
Needs more work. `_is_external` and `_remove_external_prefix` are needed to support bazelbuild/bazel#1262.

**Comment by pmbethe09** [comment]
has this been replaced by https://github.com/bazelbuild/rules_go/pull/375 ?

**Comment by jayconrod** [comment]
This has been partially replaced by #375. That PR was originally based on this one, but I split out the relevant part so we could move forward.

There is still some refactoring I'd like to do, but it's probably better to wait for bazelbuild/bazel#1262 to be fixed so we can test against that.

I'll abandon this PR for now.

**Pull request closed without merging**
