### PR TITLE
point to latest buildifier

### PR DESCRIPTION
**Pull request by pmbethe09**
switch to new import path in go and BUILD files

### CODE REVIEW

**Comment by pmbethe09** [comment]
Jenkins, test this please.

**Comment by pmbethe09** [comment]
Apparently this break at bazel < 0.4.3 since the new version uses BUILD.bazel

**Comment by twpayne** [comment]
Note that while this PR is unmerged, rules_go is broken at HEAD for `go get` users:
```
$ go get -u github.com/bazelbuild/rules_go/go/tools/gazelle/gazelle
package github.com/bazelbuild/buildifier/core: cannot find package "github.com/bazelbuild/buildifier/core" in any of:
	/usr/local/Cellar/go/1.7.5/libexec/src/github.com/bazelbuild/buildifier/core (from $GOROOT)
	/Users/twp/src/github.com/bazelbuild/buildifier/core (from $GOPATH)
```

**Comment by pmbethe09** [comment]
merging this and then hoping to fix CI next -- have confirmed that local builds on both linux and Mac work as expected.

**Pull request merged**
