### PR TITLE
Remove importpath from binary block

### PR DESCRIPTION
**Pull request by lexfrei**
Remove importpath from binary block in readme coz deprecated

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by lexfrei** [comment]
I signed it!

**Comment by jayconrod** [comment]
Travis CI got stuck and timed out. This change couldn't possibly cause a CI failure though, so force submitting.

**Comment by jayconrod** [comment]
Thanks for fixing this by the way!

**Pull request merged**
