### PR TITLE
Try to run tests on Windows

### PR DESCRIPTION
**Pull request by jayconrod**
Related #1640
Related #1775

### CODE REVIEW

**Comment by jayconrod** [comment]
cc @mhlopko @meteorcloudy @philwo 

The first error comes up pretty quickly. It looks like `git_repository` is not able to find `rm`. Do I need to do anything in .bazelci/presubmit.yml to sure `PATH`, `BAZEL_SH` and `CC` are set?

```
ERROR: error loading package '': Encountered error while reading extension file 'deps.bzl': no such package '@bazel_gazelle//': Traceback (most recent call last):
	File "C:/users/b/_bazel_b/xpzj5sdt/external/bazel_tools/tools/build_defs/repo/git.bzl", line 166
		_clone_or_update(ctx)
	File "C:/users/b/_bazel_b/xpzj5sdt/external/bazel_tools/tools/build_defs/repo/git.bzl", line 72, in _clone_or_update
		fail(("error cloning %s:\n%s" % (ctx....)))
error cloning bazel_gazelle:
+ cd C:/users/b/_bazel_b/xpzj5sdt/external
+ rm -rf C:/users/b/_bazel_b/xpzj5sdt/external/bazel_gazelle C:/users/b/_bazel_b/xpzj5sdt/external/bazel_gazelle
/usr/bin/bash: line 4: rm: command not found
Traceback (most recent call last):
  File "bazelci.py", line 1428, in <module>
    sys.exit(main())
  File "bazelci.py", line 1415, in main
    monitor_flaky_tests=args.monitor_flaky_tests)
  File "bazelci.py", line 426, in execute_commands
    print_bazel_version_info(bazel_binary)
  File "bazelci.py", line 663, in print_bazel_version_info
    execute_command([bazel_binary, "--nomaster_bazelrc", "--bazelrc=/dev/null", "info"])
  File "bazelci.py", line 995, in execute_command
    return subprocess.run(args, shell=shell, check=fail_if_nonzero, env=os.environ).returncode
  File "C:\python3\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bazel', '--nomaster_bazelrc', '--bazelrc=/dev/null', 'info']' returned non-zero exit status 2.
```

**Comment by meteorcloudy** [comment]
This could be resolved if we add MSYS bin tools directory into PATH.
@aehlig @dslomov Looks like `git_repository` has a hard dependency on Bash, even when it's not using `patch`.

**Comment by meteorcloudy** [comment]
Unfortunately, `--compiler=mingw-gcc` is broken with 0.19.0 due to https://github.com/bazelbuild/bazel/issues/6610, but `--compiler=msys-gcc` works, is it fine to use msys gcc to build cgo? @jayconrod

**Comment by jayconrod** [comment]
@meteorcloudy Any gcc-like compiler should work in theory. I haven't tried that toolchain personally though.

Should I try updating the PR? Is the Windows builder otherwise ready to go?

**Comment by meteorcloudy** [comment]
@jayconrod Yes, please try to use msys gcc, I tried on my local machine, it works. However, we might encounter some error of building shared libraries, I have some idea on how to fix it.

**Comment by jayconrod** [comment]
@meteorcloudy I tried to get msys-gcc working on my Windows machine. Turns out this will not work in Go; we need mingw-gcc specifically. The compiler works fine, but the linker has hardcoded `-lmingwex -lmingw32` into the external link command.

**Comment by meteorcloudy** [comment]
@jayconrod Do you know what's happening in the current Windows failure?
https://buildkite.com/bazel/rules-go-golang/builds/915#_

**Comment by jayconrod** [comment]
@meteorcloudy I tried to reproduce this today on my Windows machine. I ran into several issues before I got this far though.

* It's unclear to me whether Bazel is reading .bazelrc in the workspace root and in the home directory. There are warnings saying those files are not being read, but it seems like they're being read.
* Bazel can't build `@com_google_protobuf//:any_proto`, when building with `--cpu=x64_windows --compiler=mingw-gcc` (which are required for Go). This is for `@com_google_protobuf` at tag `v3.6.1.2`. Not sure about other configurations. The error message is not helpful. Any idea what's happening?

```
SUBCOMMAND: # @com_google_protobuf//:any_proto [action 'Generating Descriptor Set proto_library @com_google_protobuf//:any_proto']
cd C:/users/gopher/_bazel_gopher/gwto5adt/execroot/__main__
  SET PATH=C:\tools\msys64\usr\bin;C:\tools\msys64\bin
  bazel-out/host/bin/external/com_google_protobuf/protoc.exe --proto_path=external/com_google_protobuf --descriptor_set_out=bazel-out/x64_windows-fastbuild/genfiles/external/com_google_protobuf/any_proto-descriptor-set.proto.bin -Igoogle/protobuf/any.proto=bazel-out/x64_windows-fastbuild/genfiles/external/com_google_protobuf/google/protobuf/any.proto --direct_dependencies google/protobuf/any.proto --direct_dependencies_violation_msg=%s is imported, but @com_google_protobuf//:any_proto doesn't directly depend on a proto_library that 'srcs' it. bazel-out/x64_windows-fastbuild/genfiles/external/com_google_protobuf/google/protobuf/any.proto
```

**Comment by meteorcloudy** [comment]
@jayconrod Yes, the warning message was confusing, I think it will be fixed in the next release. You can also pass `--announce_rc` to see which rc files are read and what are the flags passed.

I have no idea what's the cause of error but I can look into this.

**Comment by meteorcloudy** [comment]
@jayconrod It turned out `--compiler=mingw-gcc` also changed the host compiler to `mingw-gcc`, that caused `protoc.exe` to be compiled with mingw, therefore it needs `C:/tools/msys64/ming64/bin` in PATH at runtime. But the path was `SET PATH=C:\tools\msys64\usr\bin;C:\tools\msys64\bin`

We can work around this by adding `build:windows --host_crosstool_top=@bazel_tools//tools/cpp:toolchain` in .bazelrc, this will set the host compiler to MSVC again. We can later change this flag to `--host_compiler=msvc-cl` when `--host_compiler` is available.

After fixing this issue, we still got this error for building Looks like we don't have `dlfcn.h` avaialble in mingw gcc, can you help fixing this issue?
```
ERROR: D:/b/bk-windows-java8-402s/bazel/rules-go-golang/tests/legacy/examples/cgo/cc_dependency/BUILD.bazel:6:1: Couldn't build file tests/legacy/examples/cgo/cc_dependency/_objs/version/cxx_version.o: C++ compilation of rule '//tests/legacy/examples/cgo/cc_dependency:version' failed (Exit 1): gcc failed: error executing command
--
  | cd D:/b/uddtxhic/execroot/io_bazel_rules_go
  | SET PATH=c:/tools/msys64/mingw64/bin
  | SET PWD=/proc/self/cwd
  | c:/tools/msys64/mingw64/bin/gcc -std=gnu++0x -MD -MF bazel-out/x64_windows-fastbuild/bin/tests/legacy/examples/cgo/cc_dependency/_objs/version/cxx_version.d -frandom-seed=bazel-out/x64_windows-fastbuild/bin/tests/legacy/examples/cgo/cc_dependency/_objs/version/cxx_version.o -iquote . -iquote bazel-out/x64_windows-fastbuild/genfiles -iquote bazel-out/x64_windows-fastbuild/bin -c tests/legacy/examples/cgo/cc_dependency/cxx_version.cc -o bazel-out/x64_windows-fastbuild/bin/tests/legacy/examples/cgo/cc_dependency/_objs/version/cxx_version.o
  | Execution platform: @bazel_tools//platforms:host_platform
  | tests/legacy/examples/cgo/cc_dependency/cxx_version.cc:1:10: fatal error: dlfcn.h: No such file or directory
  | #include <dlfcn.h>
  | ^~~~~~~~~
  | compilation terminated.

```

Errors like: 
```
ERROR: D:/b/bk-windows-java8-402s/bazel/rules-go-golang/tests/legacy/examples/cgo/BUILD.bazel:7:1: in cgo_o attribute of _cgo_import rule //tests/legacy/examples/cgo:go_default_library%linux_mips64le%cgo_import: '//tests/legacy/examples/cgo:go_default_library%linux_mips64le%_cgo_.o' must produce a single file. Since this rule was created by the macro 'go_library_macro', the error might have been caused by the macro implementation in D:/b/uddtxhic/external/io_bazel_rules_go/go/private/rules/cgo.bzl:682:17
```
are caused by not being able to build `//tests/legacy/examples/cgo/cc_dependency:version`

Looks like we don't have `dlfcn.h` avaialble in mingw gcc, can you help fixing this issue?

**Comment by jayconrod** [comment]
I'll look into the `dlfcn.h` issue as soon as I can. Bazel rules summit is tomorrow and the next day though, so I probably won't be able to until Friday.

What is the issue with mingw-gcc used as the host compiler though? That would be needed for any Go tools built for the host that rely on cgo. We don't have any such tools in rules_go, but our users might.

It seems like mingw-gcc is able to build protoc.exe successfully, but the action that runs `protoc.exe` to generate the binary descriptor is failing without an error message. Could be missing a library or something? I haven't checked yet if mingw-produced binaries are able to run in general.

**Comment by meteorcloudy** [comment]
@jayconrod Thanks!

If `protoc.exe` is compiled with mingw, it will dynamically link to some DLLs under `c:/tools/msys64/mingw64/bin`, but when running the proto action, the `PATH` was still set to `C:\tools\msys64\usr\bin;C:\tools\msys64\bin`, so `protoc.exe` couldn't find the DLL it needs, then it just fails silently.

I think if you pass `--action_env=PATH=c:/tools/msys64/mingw64/bin`, it will also allow the proto actions to pass.

**Comment by meteorcloudy** [comment]
@jayconrod Any progress on this? Is there anything I can do to help? Thanks!

**Comment by jayconrod** [comment]
@meteorcloudy The current round of failures are popping up during analysis on targets with `tags = ["manual"]`. Those targets are referenced through `select` expressions and should not be built on Windows.

I'm not seeing those errors on my test machine or on my home desktop. Is there anything about the CI setup that would cause extra targets to be analyzed?

I've seen some people report similar errors when using action listeners. Not sure if that has anything to do with this though.

**Comment by jayconrod** [comment]
@meteorcloudy Ignore my last comment. This failure was #1930. I'll rebase after #1956 is merged, and hopefully more things will work.

**Pull request merged**
