### PR TITLE
Splits the go/def.bzl file into more maintainable units.

### PR DESCRIPTION
**Pull request by pcj**
- Moves independent rules into their own .bzl file in go/private.

- Loads these independent rules in def.bzl (to preserve the same load
  interface).

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by pcj** [comment]
@pmbethe09 or @yugui can you review?  This is just a purely mechanical movement of rules that can be split into their own file.

**Comment by yugui** [comment]
LGTM.

Jenkins, test this please.

**Comment by yugui** [comment]
Oh, http://ci.bazel.io/job/PR-rules_go/112/console
> stderr: error: could not lock config file .git/config: No space left on device

**Comment by yugui** [comment]
Jenkins, retest this please.

**Comment by yugui** [comment]
Reported to bazel-dev.
https://groups.google.com/d/msg/bazel-dev/0NJz7wt-Agc/dsYsHmzZBAAJ

**Comment by pcj** [comment]
Any update on this (are all PR's blocked)?

**Comment by pmbethe09** [comment]
Sorry about that - yes we should wait to merge until the CI is fixed (already burned on that in another repo).
But I can start the review process.

**Comment by pmbethe09** [comment]
I wish there were a 'git cp' that would recognize the historical origin of each of the factored files.

LGTM, will check again on CI.

**Comment by pmbethe09** [comment]
Jenkins, retest this please.

**Pull request merged**
